package erpadm.modeladm.admam;

import erpadm.modeladm.admvo.AdminCompanyTypeVOImpl;
import erpadm.modeladm.admvo.AdminCompanyVOImpl;
import erpadm.modeladm.admvo.SysActionGroupHeaderVOImpl;
import erpadm.modeladm.admvo.SysModuleDetailVOImpl;
import erpadm.modeladm.admvo.SysPasswordParameterVOImpl;
import erpadm.modeladm.admvo.SysPasswordPolicyHeaderVOImpl;
import erpadm.modeladm.admvo.SysUsersVOImpl;

import erpglobals.modelglobals.globalsqvo.ErpUserCompanyAccessQVOImpl;

import java.sql.PreparedStatement;

import java.sql.SQLException;

import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 11 23:44:36 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ERPADMModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ERPADMModuleImpl() {
    }

    /**
     * Container's getter for SysUsersCRUD.
     * @return SysUsersCRUD
     */
    public SysUsersVOImpl getSysUsersCRUD() {
        return (SysUsersVOImpl) findViewObject("SysUsersCRUD");
    }

    /**
     * Container's getter for SysUsersRO.
     * @return SysUsersRO
     */
    public SysUsersVOImpl getSysUsersRO() {
        return (SysUsersVOImpl) findViewObject("SysUsersRO");
    }

    /**
     * Container's getter for SysUserPasswordPolicyDetCRUD.
     * @return SysUserPasswordPolicyDetCRUD
     */
    public ViewObjectImpl getSysUserPasswordPolicyDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysUserPasswordPolicyDetCRUD");
    }

    /**
     * Container's getter for AdminCompanyGroupCRUD.
     * @return AdminCompanyGroupCRUD
     */
    public AdminCompanyVOImpl getAdminCompanyGroupCRUD() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyGroupCRUD");
    }

    /**
     * Container's getter for AdminCompanyDetailCRUD.
     * @return AdminCompanyDetailCRUD
     */
    public AdminCompanyVOImpl getAdminCompanyDetailCRUD() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyDetailCRUD");
    }

    /**
     * Container's getter for AdminCompanyCRUD.
     * @return AdminCompanyCRUD
     */
    public AdminCompanyVOImpl getAdminCompanyCRUD() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyCRUD");
    }

    /**
     * Container's getter for SysActionGroupHeaderCRUD.
     * @return SysActionGroupHeaderCRUD
     */
    public SysActionGroupHeaderVOImpl getSysActionGroupHeaderCRUD() {
        return (SysActionGroupHeaderVOImpl) findViewObject("SysActionGroupHeaderCRUD");
    }

    /**
     * Container's getter for SysActionGroupLinesDetCRUD.
     * @return SysActionGroupLinesDetCRUD
     */
    public ViewObjectImpl getSysActionGroupLinesDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysActionGroupLinesDetCRUD");
    }

    /**
     * Container's getter for SysActionGroupHeaderRO.
     * @return SysActionGroupHeaderRO
     */
    public SysActionGroupHeaderVOImpl getSysActionGroupHeaderRO() {
        return (SysActionGroupHeaderVOImpl) findViewObject("SysActionGroupHeaderRO");
    }

    /**
     * Container's getter for SysModuleDetailForGroupRO.
     * @return SysModuleDetailForGroupRO
     */
    public SysModuleDetailVOImpl getSysModuleDetailForGroupRO() {
        return (SysModuleDetailVOImpl) findViewObject("SysModuleDetailForGroupRO");
    }

    /**
     * Container's getter for SysActionGroupCompanyDetCRUD.
     * @return SysActionGroupCompanyDetCRUD
     */
    public ViewObjectImpl getSysActionGroupCompanyDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysActionGroupCompanyDetCRUD");
    }

    /**
     * Container's getter for SysActionGroupLinesCompanyDetCRUD.
     * @return SysActionGroupLinesCompanyDetCRUD
     */
    public ViewObjectImpl getSysActionGroupLinesCompanyDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysActionGroupLinesCompanyDetCRUD");
    }

    /**
     * Container's getter for AdminCompanyGroupActLinAssignRO.
     * @return AdminCompanyGroupActLinAssignRO
     */
    public AdminCompanyVOImpl getAdminCompanyGroupActLinAssignRO() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyGroupActLinAssignRO");
    }

    /**
     * Container's getter for AdminCompanyRO.
     * @return AdminCompanyRO
     */
    public AdminCompanyVOImpl getAdminCompanyRO() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyRO");
    }

    /**
     * Container's getter for AdminCompanyGroupActAssignRO.
     * @return AdminCompanyGroupActAssignRO
     */
    public AdminCompanyVOImpl getAdminCompanyGroupActAssignRO() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyGroupActAssignRO");
    }

    /**
     * Container's getter for SysUsersModuleDetCRUD.
     * @return SysUsersModuleDetCRUD
     */
    public ViewObjectImpl getSysUsersModuleDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysUsersModuleDetCRUD");
    }

    /**
     * Container's getter for SysModuleDetailUserAssignRO.
     * @return SysModuleDetailUserAssignRO
     */
    public SysModuleDetailVOImpl getSysModuleDetailUserAssignRO() {
        return (SysModuleDetailVOImpl) findViewObject("SysModuleDetailUserAssignRO");
    }

    /**
     * Container's getter for SysUsersModuleCompanyDetCRUD.
     * @return SysUsersModuleCompanyDetCRUD
     */
    public ViewObjectImpl getSysUsersModuleCompanyDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysUsersModuleCompanyDetCRUD");
    }

    /**
     * Container's getter for AdminCompanyAssignUserActionRO.
     * @return AdminCompanyAssignUserActionRO
     */
    public AdminCompanyVOImpl getAdminCompanyAssignUserActionRO() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyAssignUserActionRO");
    }

    /**
     * Container's getter for AdminCompanyAssignUserRO.
     * @return AdminCompanyAssignUserRO
     */
    public AdminCompanyVOImpl getAdminCompanyAssignUserRO() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyAssignUserRO");
    }

    /**
     * Container's getter for SysUserCompanyDetCRUD.
     * @return SysUserCompanyDetCRUD
     */
    public ViewObjectImpl getSysUserCompanyDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysUserCompanyDetCRUD");
    }

    /**
     * Container's getter for SysActionGroupUserDetCRUD.
     * @return SysActionGroupUserDetCRUD
     */
    public ViewObjectImpl getSysActionGroupUserDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysActionGroupUserDetCRUD");
    }

    /**
     * Container's getter for SysActionGroupUsrGroupDetCRUD.
     * @return SysActionGroupUsrGroupDetCRUD
     */
    public ViewObjectImpl getSysActionGroupUsrGroupDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysActionGroupUsrGroupDetCRUD");
    }

    /**
     * Container's getter for SysActionGroupHeadAssignUserRO.
     * @return SysActionGroupHeadAssignUserRO
     */
    public SysActionGroupHeaderVOImpl getSysActionGroupHeadAssignUserRO() {
        return (SysActionGroupHeaderVOImpl) findViewObject("SysActionGroupHeadAssignUserRO");
    }

    /**
     * Container's getter for SysUsersAssignActionGroupUserRO.
     * @return SysUsersAssignActionGroupUserRO
     */
    public SysUsersVOImpl getSysUsersAssignActionGroupUserRO() {
        return (SysUsersVOImpl) findViewObject("SysUsersAssignActionGroupUserRO");
    }

    /**
     * Container's getter for ErpUserCompanyAccessRO.
     * @return ErpUserCompanyAccessRO
     */
    public ErpUserCompanyAccessQVOImpl getErpUserCompanyAccessRO() {
        return (ErpUserCompanyAccessQVOImpl) findViewObject("ErpUserCompanyAccessRO");
    }

    /**
     * Container's getter for SmCountryRO.
     * @return SmCountryRO
     */
    public ViewObjectImpl getSmCountryRO() {
        return (ViewObjectImpl) findViewObject("SmCountryRO");
    }

    /**
     * Container's getter for SmCountryCRUD.
     * @return SmCountryCRUD
     */
    public ViewObjectImpl getSmCountryCRUD() {
        return (ViewObjectImpl) findViewObject("SmCountryCRUD");
    }

    /**
     * Container's getter for SmCityDetCRUD.
     * @return SmCityDetCRUD
     */
    public ViewObjectImpl getSmCityDetCRUD() {
        return (ViewObjectImpl) findViewObject("SmCityDetCRUD");
    }

    /**
     * Container's getter for SmCityRO.
     * @return SmCityRO
     */
    public ViewObjectImpl getSmCityRO() {
        return (ViewObjectImpl) findViewObject("SmCityRO");
    }

    /**
     * Container's getter for SmCityCRUD.
     * @return SmCityCRUD
     */
    public ViewObjectImpl getSmCityCRUD() {
        return (ViewObjectImpl) findViewObject("SmCityCRUD");
    }

    /**
     * Container's getter for AdminCompanyCategorizationRO.
     * @return AdminCompanyCategorizationRO
     */
    public AdminCompanyVOImpl getAdminCompanyCategorizationRO() {
        return (AdminCompanyVOImpl) findViewObject("AdminCompanyCategorizationRO");
    }

    /**
     * Container's getter for AdminCompantNextTypesRO.
     * @return AdminCompantNextTypesRO
     */
    public ViewObjectImpl getAdminCompantNextTypesRO() {
        return (ViewObjectImpl) findViewObject("AdminCompantNextTypesRO");
    }

    /**
     * Container's getter for AdminCompanyTypeRO.
     * @return AdminCompanyTypeRO
     */
    public AdminCompanyTypeVOImpl getAdminCompanyTypeRO() {
        return (AdminCompanyTypeVOImpl) findViewObject("AdminCompanyTypeRO");
    }

    /**
     * Container's getter for AdminCompanyTypeCRUD.
     * @return AdminCompanyTypeCRUD
     */
    public AdminCompanyTypeVOImpl getAdminCompanyTypeCRUD() {
        return (AdminCompanyTypeVOImpl) findViewObject("AdminCompanyTypeCRUD");
    }

    /**
     * Container's getter for AdminCompanyTypeHierarchyRO.
     * @return AdminCompanyTypeHierarchyRO
     */
    public AdminCompanyTypeVOImpl getAdminCompanyTypeHierarchyRO() {
        return (AdminCompanyTypeVOImpl) findViewObject("AdminCompanyTypeHierarchyRO");
    }

    /**
     * Container's getter for SysGeneralValueSetRO.
     * @return SysGeneralValueSetRO
     */
    public ViewObjectImpl getSysGeneralValueSetRO() {
        return (ViewObjectImpl) findViewObject("SysGeneralValueSetRO");
    }

    /**
     * Container's getter for SysGeneralValueSetCRUD.
     * @return SysGeneralValueSetCRUD
     */
    public ViewObjectImpl getSysGeneralValueSetCRUD() {
        return (ViewObjectImpl) findViewObject("SysGeneralValueSetCRUD");
    }

    /**
     * Container's getter for SysGeneralValueDetCRUD.
     * @return SysGeneralValueDetCRUD
     */
    public ViewObjectImpl getSysGeneralValueDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysGeneralValueDetCRUD");
    }

    /**
     * Container's getter for SysGeneralValueDetRO.
     * @return SysGeneralValueDetRO
     */
    public ViewObjectImpl getSysGeneralValueDetRO() {
        return (ViewObjectImpl) findViewObject("SysGeneralValueDetRO");
    }

    /**
     * Container's getter for SysParametersCRUD.
     * @return SysParametersCRUD
     */
    public ViewObjectImpl getSysParametersCRUD() {
        return (ViewObjectImpl) findViewObject("SysParametersCRUD");
    }

    /**
     * Container's getter for SysPasswordPolicyHeaderCRUD.
     * @return SysPasswordPolicyHeaderCRUD
     */
    public SysPasswordPolicyHeaderVOImpl getSysPasswordPolicyHeaderCRUD() {
        return (SysPasswordPolicyHeaderVOImpl) findViewObject("SysPasswordPolicyHeaderCRUD");
    }

    /**
     * Container's getter for SysPasswordPolicyLinesDetCRUD.
     * @return SysPasswordPolicyLinesDetCRUD
     */
    public ViewObjectImpl getSysPasswordPolicyLinesDetCRUD() {
        return (ViewObjectImpl) findViewObject("SysPasswordPolicyLinesDetCRUD");
    }

    /**
     * Container's getter for SysPasswordPolicyHeaderRO.
     * @return SysPasswordPolicyHeaderRO
     */
    public SysPasswordPolicyHeaderVOImpl getSysPasswordPolicyHeaderRO() {
        return (SysPasswordPolicyHeaderVOImpl) findViewObject("SysPasswordPolicyHeaderRO");
    }

    /**
     * Container's getter for SysPasswordParameterForPolicyRO.
     * @return SysPasswordParameterForPolicyRO
     */
    public SysPasswordParameterVOImpl getSysPasswordParameterForPolicyRO() {
        return (SysPasswordParameterVOImpl) findViewObject("SysPasswordParameterForPolicyRO");
    }

    /**
     * Container's getter for FkSysUserPwdPolUserIdLink2.
     * @return FkSysUserPwdPolUserIdLink2
     */
    public ViewLinkImpl getFkSysUserPwdPolUserIdLink2() {
        return (ViewLinkImpl) findViewLink("FkSysUserPwdPolUserIdLink2");
    }

    /**
     * Container's getter for AdminCompanyIdAdminCompParentVL1.
     * @return AdminCompanyIdAdminCompParentVL1
     */
    public ViewLinkImpl getAdminCompanyIdAdminCompParentVL1() {
        return (ViewLinkImpl) findViewLink("AdminCompanyIdAdminCompParentVL1");
    }

    /**
     * Container's getter for FkSysActGrpLinHeaderLink1.
     * @return FkSysActGrpLinHeaderLink1
     */
    public ViewLinkImpl getFkSysActGrpLinHeaderLink1() {
        return (ViewLinkImpl) findViewLink("FkSysActGrpLinHeaderLink1");
    }

    /**
     * Container's getter for SysActGroupSysActGroupCompGroupIdVL1.
     * @return SysActGroupSysActGroupCompGroupIdVL1
     */
    public ViewLinkImpl getSysActGroupSysActGroupCompGroupIdVL1() {
        return (ViewLinkImpl) findViewLink("SysActGroupSysActGroupCompGroupIdVL1");
    }

    /**
     * Container's getter for SysActGrpLinSysActGrpLinCompGroupLinesSnoVL1.
     * @return SysActGrpLinSysActGrpLinCompGroupLinesSnoVL1
     */
    public ViewLinkImpl getSysActGrpLinSysActGrpLinCompGroupLinesSnoVL1() {
        return (ViewLinkImpl) findViewLink("SysActGrpLinSysActGrpLinCompGroupLinesSnoVL1");
    }

    /**
     * Container's getter for SysUsersSysUsersModuleUserIdVL1.
     * @return SysUsersSysUsersModuleUserIdVL1
     */
    public ViewLinkImpl getSysUsersSysUsersModuleUserIdVL1() {
        return (ViewLinkImpl) findViewLink("SysUsersSysUsersModuleUserIdVL1");
    }

    /**
     * Container's getter for SysUsersModuleSysUserModComModActIDVL1.
     * @return SysUsersModuleSysUserModComModActIDVL1
     */
    public ViewLinkImpl getSysUsersModuleSysUserModComModActIDVL1() {
        return (ViewLinkImpl) findViewLink("SysUsersModuleSysUserModComModActIDVL1");
    }

    /**
     * Container's getter for SysUsersSysUserCompanyUserIDVL1.
     * @return SysUsersSysUserCompanyUserIDVL1
     */
    public ViewLinkImpl getSysUsersSysUserCompanyUserIDVL1() {
        return (ViewLinkImpl) findViewLink("SysUsersSysUserCompanyUserIDVL1");
    }

    /**
     * Container's getter for SysUsersSysActionGroupUserUserIdVL1.
     * @return SysUsersSysActionGroupUserUserIdVL1
     */
    public ViewLinkImpl getSysUsersSysActionGroupUserUserIdVL1() {
        return (ViewLinkImpl) findViewLink("SysUsersSysActionGroupUserUserIdVL1");
    }

    /**
     * Container's getter for SysActionGroupHeadSysActionGroupUserVL1.
     * @return SysActionGroupHeadSysActionGroupUserVL1
     */
    public ViewLinkImpl getSysActionGroupHeadSysActionGroupUserVL1() {
        return (ViewLinkImpl) findViewLink("SysActionGroupHeadSysActionGroupUserVL1");
    }

    /**
     * Container's getter for SmCountrySmCityCountrySnoVL1.
     * @return SmCountrySmCityCountrySnoVL1
     */
    public ViewLinkImpl getSmCountrySmCityCountrySnoVL1() {
        return (ViewLinkImpl) findViewLink("SmCountrySmCityCountrySnoVL1");
    }

    /**
     * Container's getter for FkGenValueValueSetIdLink1.
     * @return FkGenValueValueSetIdLink1
     */
    public ViewLinkImpl getFkGenValueValueSetIdLink1() {
        return (ViewLinkImpl) findViewLink("FkGenValueValueSetIdLink1");
    }

    /**
     * Container's getter for FkGenValueValueSetIdLink2.
     * @return FkGenValueValueSetIdLink2
     */
    public ViewLinkImpl getFkGenValueValueSetIdLink2() {
        return (ViewLinkImpl) findViewLink("FkGenValueValueSetIdLink2");
    }

    /**
     * Container's getter for FkSysPwPolLinPolHeadSnoLink1.
     * @return FkSysPwPolLinPolHeadSnoLink1
     */
    public ViewLinkImpl getFkSysPwPolLinPolHeadSnoLink1() {
        return (ViewLinkImpl) findViewLink("FkSysPwPolLinPolHeadSnoLink1");
    }
    @Override
    protected void prepareSession(Session session) {
        // TODO Implement this method
        String sqlquery =" SET AUTOCOMMIT = 0";
        PreparedStatement ps = getDBTransaction().createPreparedStatement(sqlquery, 1);
        try {
            ps.executeUpdate();
        } catch (SQLException e) {
        }
        super.prepareSession(session);
    }

    /**
     * Container's getter for SysUsersModuleVO1.
     * @return SysUsersModuleVO1
     */
    public ViewObjectImpl getSysUsersModuleVO1() {
        return (ViewObjectImpl) findViewObject("SysUsersModuleVO1");
    }

    /**
     * Container's getter for SysGeneralValueVO1.
     * @return SysGeneralValueVO1
     */
    public ViewObjectImpl getSysGeneralValueStorePathRO() {
        return (ViewObjectImpl) findViewObject("SysGeneralValueStorePathRO");
    }

    /**
     * Container's getter for SysGeneralValueVO2.
     * @return SysGeneralValueVO2
     */
    public ViewObjectImpl getSysGeneralValueStoreOnRO() {
        return (ViewObjectImpl) findViewObject("SysGeneralValueStoreOnRO");
    }
}

