package erpadm.modeladm.admeo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 18 17:35:03 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminCompanyImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CompCode,
        CompanyName,
        Address,
        Gstno,
        Ntnno,
        Phone,
        Fax,
        CountryId,
        CityId,
        Active,
        CompanyTypeSno,
        ParentCompCode,
        ContactPerson,
        CompanyShortCode,
        CompanyShortName,
        MobileNo,
        CurrencySno,
        RegistrationNo,
        BusinessStartDate,
        Email,
        Website,
        GlobalCompCode,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        CompanyHierarchyPath,
        txtParentHierarchyPath,
        AdminBranches,
        AdminCompany,
        ParentCompCodeAdminCompany,
        SysActionGroupCompany,
        SysActionGroupLinesCompany,
        SysUsersModuleCompany,
        SysUserCompany,
        AdminCompanyType,
        AccAdminCompanyDupGlobalTypeVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPCODE = AttributesEnum.CompCode.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int GSTNO = AttributesEnum.Gstno.index();
    public static final int NTNNO = AttributesEnum.Ntnno.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int FAX = AttributesEnum.Fax.index();
    public static final int COUNTRYID = AttributesEnum.CountryId.index();
    public static final int CITYID = AttributesEnum.CityId.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int COMPANYTYPESNO = AttributesEnum.CompanyTypeSno.index();
    public static final int PARENTCOMPCODE = AttributesEnum.ParentCompCode.index();
    public static final int CONTACTPERSON = AttributesEnum.ContactPerson.index();
    public static final int COMPANYSHORTCODE = AttributesEnum.CompanyShortCode.index();
    public static final int COMPANYSHORTNAME = AttributesEnum.CompanyShortName.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int CURRENCYSNO = AttributesEnum.CurrencySno.index();
    public static final int REGISTRATIONNO = AttributesEnum.RegistrationNo.index();
    public static final int BUSINESSSTARTDATE = AttributesEnum.BusinessStartDate.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int WEBSITE = AttributesEnum.Website.index();
    public static final int GLOBALCOMPCODE = AttributesEnum.GlobalCompCode.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int COMPANYHIERARCHYPATH = AttributesEnum.CompanyHierarchyPath.index();
    public static final int TXTPARENTHIERARCHYPATH = AttributesEnum.txtParentHierarchyPath.index();
    public static final int ADMINBRANCHES = AttributesEnum.AdminBranches.index();
    public static final int ADMINCOMPANY = AttributesEnum.AdminCompany.index();
    public static final int PARENTCOMPCODEADMINCOMPANY = AttributesEnum.ParentCompCodeAdminCompany.index();
    public static final int SYSACTIONGROUPCOMPANY = AttributesEnum.SysActionGroupCompany.index();
    public static final int SYSACTIONGROUPLINESCOMPANY = AttributesEnum.SysActionGroupLinesCompany.index();
    public static final int SYSUSERSMODULECOMPANY = AttributesEnum.SysUsersModuleCompany.index();
    public static final int SYSUSERCOMPANY = AttributesEnum.SysUserCompany.index();
    public static final int ADMINCOMPANYTYPE = AttributesEnum.AdminCompanyType.index();
    public static final int ACCADMINCOMPANYDUPGLOBALTYPEVO = AttributesEnum.AccAdminCompanyDupGlobalTypeVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AdminCompanyImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpadm.modeladm.admeo.AdminCompany");
    }


    /**
     * Gets the attribute value for CompCode, using the alias name CompCode.
     * @return the value of CompCode
     */
    public BigDecimal getCompCode() {
        return (BigDecimal) getAttributeInternal(COMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompCode.
     * @param value value to set the CompCode
     */
    public void setCompCode(BigDecimal value) {
        setAttributeInternal(COMPCODE, value);
    }

    /**
     * Gets the attribute value for CompanyName, using the alias name CompanyName.
     * @return the value of CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyName.
     * @param value value to set the CompanyName
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value==null?null:value.toUpperCase() );
    }

    /**
     * Gets the attribute value for Address, using the alias name Address.
     * @return the value of Address
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Address.
     * @param value value to set the Address
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for Gstno, using the alias name Gstno.
     * @return the value of Gstno
     */
    public String getGstno() {
        return (String) getAttributeInternal(GSTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gstno.
     * @param value value to set the Gstno
     */
    public void setGstno(String value) {
        setAttributeInternal(GSTNO, value);
    }

    /**
     * Gets the attribute value for Ntnno, using the alias name Ntnno.
     * @return the value of Ntnno
     */
    public String getNtnno() {
        return (String) getAttributeInternal(NTNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ntnno.
     * @param value value to set the Ntnno
     */
    public void setNtnno(String value) {
        setAttributeInternal(NTNNO, value);
    }

    /**
     * Gets the attribute value for Phone, using the alias name Phone.
     * @return the value of Phone
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Phone.
     * @param value value to set the Phone
     */
    public void setPhone(String value) {
        setAttributeInternal(PHONE, value);
    }

    /**
     * Gets the attribute value for Fax, using the alias name Fax.
     * @return the value of Fax
     */
    public String getFax() {
        return (String) getAttributeInternal(FAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fax.
     * @param value value to set the Fax
     */
    public void setFax(String value) {
        setAttributeInternal(FAX, value);
    }

    /**
     * Gets the attribute value for CountryId, using the alias name CountryId.
     * @return the value of CountryId
     */
    public Integer getCountryId() {
        return (Integer) getAttributeInternal(COUNTRYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountryId.
     * @param value value to set the CountryId
     */
    public void setCountryId(Integer value) {
        setAttributeInternal(COUNTRYID, value);
    }

    /**
     * Gets the attribute value for CityId, using the alias name CityId.
     * @return the value of CityId
     */
    public String getCityId() {
        return (String) getAttributeInternal(CITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CityId.
     * @param value value to set the CityId
     */
    public void setCityId(String value) {
        setAttributeInternal(CITYID, value);
    }

    /**
     * Gets the attribute value for Active, using the alias name Active.
     * @return the value of Active
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Active.
     * @param value value to set the Active
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for CompanyTypeSno, using the alias name CompanyTypeSno.
     * @return the value of CompanyTypeSno
     */
    public Integer getCompanyTypeSno() {
        return (Integer) getAttributeInternal(COMPANYTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyTypeSno.
     * @param value value to set the CompanyTypeSno
     */
    public void setCompanyTypeSno(Integer value) {
        setAttributeInternal(COMPANYTYPESNO, value);
    }

    /**
     * Gets the attribute value for ParentCompCode, using the alias name ParentCompCode.
     * @return the value of ParentCompCode
     */
    public Integer getParentCompCode() {
        return (Integer) getAttributeInternal(PARENTCOMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentCompCode.
     * @param value value to set the ParentCompCode
     */
    public void setParentCompCode(Integer value) {
        setAttributeInternal(PARENTCOMPCODE, value);
    }

    /**
     * Gets the attribute value for ContactPerson, using the alias name ContactPerson.
     * @return the value of ContactPerson
     */
    public String getContactPerson() {
        return (String) getAttributeInternal(CONTACTPERSON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactPerson.
     * @param value value to set the ContactPerson
     */
    public void setContactPerson(String value) {
        setAttributeInternal(CONTACTPERSON, value);
    }

    /**
     * Gets the attribute value for CompanyShortCode, using the alias name CompanyShortCode.
     * @return the value of CompanyShortCode
     */
    public Integer getCompanyShortCode() {
        return (Integer) getAttributeInternal(COMPANYSHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyShortCode.
     * @param value value to set the CompanyShortCode
     */
    public void setCompanyShortCode(Integer value) {
        setAttributeInternal(COMPANYSHORTCODE, value);
    }

    /**
     * Gets the attribute value for CompanyShortName, using the alias name CompanyShortName.
     * @return the value of CompanyShortName
     */
    public String getCompanyShortName() {
        return (String) getAttributeInternal(COMPANYSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyShortName.
     * @param value value to set the CompanyShortName
     */
    public void setCompanyShortName(String value) {
        setAttributeInternal(COMPANYSHORTNAME, value==null?null:value.toUpperCase());
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the value of MobileNo
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for CurrencySno, using the alias name CurrencySno.
     * @return the value of CurrencySno
     */
    public Integer getCurrencySno() {
        return (Integer) getAttributeInternal(CURRENCYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrencySno.
     * @param value value to set the CurrencySno
     */
    public void setCurrencySno(Integer value) {
        setAttributeInternal(CURRENCYSNO, value);
    }

    /**
     * Gets the attribute value for RegistrationNo, using the alias name RegistrationNo.
     * @return the value of RegistrationNo
     */
    public String getRegistrationNo() {
        return (String) getAttributeInternal(REGISTRATIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RegistrationNo.
     * @param value value to set the RegistrationNo
     */
    public void setRegistrationNo(String value) {
        setAttributeInternal(REGISTRATIONNO, value);
    }

    /**
     * Gets the attribute value for BusinessStartDate, using the alias name BusinessStartDate.
     * @return the value of BusinessStartDate
     */
    public Timestamp getBusinessStartDate() {
        return (Timestamp) getAttributeInternal(BUSINESSSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessStartDate.
     * @param value value to set the BusinessStartDate
     */
    public void setBusinessStartDate(Timestamp value) {
        setAttributeInternal(BUSINESSSTARTDATE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Website, using the alias name Website.
     * @return the value of Website
     */
    public String getWebsite() {
        return (String) getAttributeInternal(WEBSITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Website.
     * @param value value to set the Website
     */
    public void setWebsite(String value) {
        setAttributeInternal(WEBSITE, value);
    }

    /**
     * Gets the attribute value for GlobalCompCode, using the alias name GlobalCompCode.
     * @return the value of GlobalCompCode
     */
    public Long getGlobalCompCode() {
        return (Long) getAttributeInternal(GLOBALCOMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompCode.
     * @param value value to set the GlobalCompCode
     */
    public void setGlobalCompCode(Long value) {
        setAttributeInternal(GLOBALCOMPCODE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for CompanyHierarchyPath, using the alias name CompanyHierarchyPath.
     * @return the value of CompanyHierarchyPath
     */
    public String getCompanyHierarchyPath() {
        return (String) getAttributeInternal(COMPANYHIERARCHYPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyHierarchyPath.
     * @param value value to set the CompanyHierarchyPath
     */
    public void setCompanyHierarchyPath(String value) {
        setAttributeInternal(COMPANYHIERARCHYPATH, value);
    }

    /**
     * Gets the attribute value for txtParentHierarchyPath, using the alias name txtParentHierarchyPath.
     * @return the value of txtParentHierarchyPath
     */
    public String gettxtParentHierarchyPath() {
        return (String) getAttributeInternal(TXTPARENTHIERARCHYPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtParentHierarchyPath.
     * @param value value to set the txtParentHierarchyPath
     */
    public void settxtParentHierarchyPath(String value) {
        setAttributeInternal(TXTPARENTHIERARCHYPATH, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAdminBranches() {
        return (RowIterator) getAttributeInternal(ADMINBRANCHES);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAdminCompany() {
        return (RowIterator) getAttributeInternal(ADMINCOMPANY);
    }

    /**
     * @return the associated entity AdminCompanyImpl.
     */
    public AdminCompanyImpl getParentCompCodeAdminCompany() {
        return (AdminCompanyImpl) getAttributeInternal(PARENTCOMPCODEADMINCOMPANY);
    }

    /**
     * Sets <code>value</code> as the associated entity AdminCompanyImpl.
     */
    public void setParentCompCodeAdminCompany(AdminCompanyImpl value) {
        setAttributeInternal(PARENTCOMPCODEADMINCOMPANY, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSysActionGroupCompany() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPCOMPANY);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSysActionGroupLinesCompany() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPLINESCOMPANY);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSysUsersModuleCompany() {
        return (RowIterator) getAttributeInternal(SYSUSERSMODULECOMPANY);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSysUserCompany() {
        return (RowIterator) getAttributeInternal(SYSUSERCOMPANY);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public AdminCompanyTypeImpl getAdminCompanyType() {
        return (AdminCompanyTypeImpl) getAttributeInternal(ADMINCOMPANYTYPE);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAdminCompanyType(AdminCompanyTypeImpl value) {
        setAttributeInternal(ADMINCOMPANYTYPE, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyDupGlobalTypeVO.
     */
    public RowSet getAccAdminCompanyDupGlobalTypeVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYDUPGLOBALTYPEVO);
    }


    /**
     * @param compCode key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal compCode) {
        return new Key(new Object[] { compCode });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "COMP_CODE",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(COMPANYHIERARCHYPATH,getParentCompCode()==0?result:gettxtParentHierarchyPath()+"-".concat(result));
             
           populateAttributeAsChanged(COMPCODE, new BigDecimal(result));
           result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "COMPANY_SHORT_CODE",this.getEntityDef().getSource(), "GLOBAL_COMP_CODE",getGlobalCompCode().toString());
           populateAttributeAsChanged(COMPANYSHORTCODE, Integer.parseInt(result));
        }        
        super.doDML(operation, e);
    }
}

