package erpadm.modeladm.admeo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 14 12:05:35 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysActionGroupUserImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GroupUserSno,
        GroupHeaderSno,
        UserId,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        SysUsers,
        SysActionGroupHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GROUPUSERSNO = AttributesEnum.GroupUserSno.index();
    public static final int GROUPHEADERSNO = AttributesEnum.GroupHeaderSno.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SYSUSERS = AttributesEnum.SysUsers.index();
    public static final int SYSACTIONGROUPHEADER = AttributesEnum.SysActionGroupHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysActionGroupUserImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpadm.modeladm.admeo.SysActionGroupUser");
    }


    /**
     * Gets the attribute value for GroupUserSno, using the alias name GroupUserSno.
     * @return the value of GroupUserSno
     */
    public Integer getGroupUserSno() {
        return (Integer) getAttributeInternal(GROUPUSERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupUserSno.
     * @param value value to set the GroupUserSno
     */
    public void setGroupUserSno(Integer value) {
        setAttributeInternal(GROUPUSERSNO, value);
    }

    /**
     * Gets the attribute value for GroupHeaderSno, using the alias name GroupHeaderSno.
     * @return the value of GroupHeaderSno
     */
    public Integer getGroupHeaderSno() {
        return (Integer) getAttributeInternal(GROUPHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupHeaderSno.
     * @param value value to set the GroupHeaderSno
     */
    public void setGroupHeaderSno(Integer value) {
        setAttributeInternal(GROUPHEADERSNO, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(Integer value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * @return the associated entity SysUsersImpl.
     */
    public SysUsersImpl getSysUsers() {
        return (SysUsersImpl) getAttributeInternal(SYSUSERS);
    }

    /**
     * Sets <code>value</code> as the associated entity SysUsersImpl.
     */
    public void setSysUsers(SysUsersImpl value) {
        setAttributeInternal(SYSUSERS, value);
    }

    /**
     * @return the associated entity SysActionGroupHeaderImpl.
     */
    public SysActionGroupHeaderImpl getSysActionGroupHeader() {
        return (SysActionGroupHeaderImpl) getAttributeInternal(SYSACTIONGROUPHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity SysActionGroupHeaderImpl.
     */
    public void setSysActionGroupHeader(SysActionGroupHeaderImpl value) {
        setAttributeInternal(SYSACTIONGROUPHEADER, value);
    }


    /**
     * @param groupUserSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer groupUserSno) {
        return new Key(new Object[] { groupUserSno });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "GROUP_USER_SNO",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(GROUPUSERSNO, Long.parseLong(result));
        }  
        super.doDML(operation, e);
    }
}

