package erpadm.modeladm.admeo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 29 12:25:42 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysActionGroupCompanyImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GroupCompanySno,
        GroupHeaderSno,
        CompanyId,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        GlobalCompanyId,
        txtCompanyName,
        txtCompanyShortCode,
        SysActionGroupHeader,
        AdminCompany;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GROUPCOMPANYSNO = AttributesEnum.GroupCompanySno.index();
    public static final int GROUPHEADERSNO = AttributesEnum.GroupHeaderSno.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int TXTCOMPANYNAME = AttributesEnum.txtCompanyName.index();
    public static final int TXTCOMPANYSHORTCODE = AttributesEnum.txtCompanyShortCode.index();
    public static final int SYSACTIONGROUPHEADER = AttributesEnum.SysActionGroupHeader.index();
    public static final int ADMINCOMPANY = AttributesEnum.AdminCompany.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysActionGroupCompanyImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpadm.modeladm.admeo.SysActionGroupCompany");
    }


    /**
     * Gets the attribute value for GroupCompanySno, using the alias name GroupCompanySno.
     * @return the value of GroupCompanySno
     */
    public Long getGroupCompanySno() {
        return (Long) getAttributeInternal(GROUPCOMPANYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupCompanySno.
     * @param value value to set the GroupCompanySno
     */
    public void setGroupCompanySno(Long value) {
        setAttributeInternal(GROUPCOMPANYSNO, value);
    }

    /**
     * Gets the attribute value for GroupHeaderSno, using the alias name GroupHeaderSno.
     * @return the value of GroupHeaderSno
     */
    public Long getGroupHeaderSno() {
        return (Long) getAttributeInternal(GROUPHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupHeaderSno.
     * @param value value to set the GroupHeaderSno
     */
    public void setGroupHeaderSno(Long value) {
        setAttributeInternal(GROUPHEADERSNO, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for txtCompanyName, using the alias name txtCompanyName.
     * @return the value of txtCompanyName
     */
    public String gettxtCompanyName() {
        return (String) getAttributeInternal(TXTCOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCompanyName.
     * @param value value to set the txtCompanyName
     */
    public void settxtCompanyName(String value) {
        setAttributeInternal(TXTCOMPANYNAME, value);
    }


    /**
     * Gets the attribute value for txtCompanyShortCode, using the alias name txtCompanyShortCode.
     * @return the value of txtCompanyShortCode
     */
    public Integer gettxtCompanyShortCode() {
        return (Integer) getAttributeInternal(TXTCOMPANYSHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCompanyShortCode.
     * @param value value to set the txtCompanyShortCode
     */
    public void settxtCompanyShortCode(Integer value) {
        setAttributeInternal(TXTCOMPANYSHORTCODE, value);
    }

    /**
     * @return the associated entity SysActionGroupHeaderImpl.
     */
    public SysActionGroupHeaderImpl getSysActionGroupHeader() {
        return (SysActionGroupHeaderImpl) getAttributeInternal(SYSACTIONGROUPHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity SysActionGroupHeaderImpl.
     */
    public void setSysActionGroupHeader(SysActionGroupHeaderImpl value) {
        setAttributeInternal(SYSACTIONGROUPHEADER, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public AdminCompanyImpl getAdminCompany() {
        return (AdminCompanyImpl) getAttributeInternal(ADMINCOMPANY);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAdminCompany(AdminCompanyImpl value) {
        setAttributeInternal(ADMINCOMPANY, value);
    }


    /**
     * @param groupCompanySno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long groupCompanySno) {
        return new Key(new Object[] { groupCompanySno });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "GROUP_COMPANY_SNO",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(GROUPCOMPANYSNO, Integer.parseInt(result));
        }       
              
        super.doDML(operation, e);
    }
}

