package erpadm.modeladm.admeo;

import erpglobals.modelglobals.ERPEntityImpl;

import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 24 17:10:57 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysGeneralValueImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ValueId,
        ValueDescription,
        ValueSetId,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        IsActive,
        ValueCode,
        SysGeneralValueSet;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int VALUEID = AttributesEnum.ValueId.index();
    public static final int VALUEDESCRIPTION = AttributesEnum.ValueDescription.index();
    public static final int VALUESETID = AttributesEnum.ValueSetId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int VALUECODE = AttributesEnum.ValueCode.index();
    public static final int SYSGENERALVALUESET = AttributesEnum.SysGeneralValueSet.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysGeneralValueImpl() {
    }

    /**
     * Gets the attribute value for ValueId, using the alias name ValueId.
     * @return the value of ValueId
     */
    public Integer getValueId() {
        return (Integer) getAttributeInternal(VALUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueId.
     * @param value value to set the ValueId
     */
    public void setValueId(Integer value) {
        setAttributeInternal(VALUEID, value);
    }

    /**
     * Gets the attribute value for ValueDescription, using the alias name ValueDescription.
     * @return the value of ValueDescription
     */
    public String getValueDescription() {
        return (String) getAttributeInternal(VALUEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueDescription.
     * @param value value to set the ValueDescription
     */
    public void setValueDescription(String value) {
        setAttributeInternal(VALUEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ValueSetId, using the alias name ValueSetId.
     * @return the value of ValueSetId
     */
    public Integer getValueSetId() {
        return (Integer) getAttributeInternal(VALUESETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueSetId.
     * @param value value to set the ValueSetId
     */
    public void setValueSetId(Integer value) {
        setAttributeInternal(VALUESETID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for ValueCode, using the alias name ValueCode.
     * @return the value of ValueCode
     */
    public String getValueCode() {
        return (String) getAttributeInternal(VALUECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueCode.
     * @param value value to set the ValueCode
     */
    public void setValueCode(String value) {
        setAttributeInternal(VALUECODE, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getSysGeneralValueSet() {
        return (EntityImpl) getAttributeInternal(SYSGENERALVALUESET);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setSysGeneralValueSet(EntityImpl value) {
        setAttributeInternal(SYSGENERALVALUESET, value);
    }

    /**
     * @param valueId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer valueId) {
        return new Key(new Object[] { valueId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpadm.modeladm.admeo.SysGeneralValue");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "VALUE_ID",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(VALUEID, Integer.parseInt(result));
        }        
        super.doDML(operation, e);
    }
}

