package erpadm.modeladm.admeo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Key;
import oracle.jbo.ViewObject;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 18 22:30:44 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysPasswordPolicyLinesImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PolicyLinesSno,
        PolicyHeaderSno,
        PasswordParameterSno,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        SysPasswordPolicyHeader,
        SysPasswordParameter;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int POLICYLINESSNO = AttributesEnum.PolicyLinesSno.index();
    public static final int POLICYHEADERSNO = AttributesEnum.PolicyHeaderSno.index();
    public static final int PASSWORDPARAMETERSNO = AttributesEnum.PasswordParameterSno.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SYSPASSWORDPOLICYHEADER = AttributesEnum.SysPasswordPolicyHeader.index();
    public static final int SYSPASSWORDPARAMETER = AttributesEnum.SysPasswordParameter.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysPasswordPolicyLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpadm.modeladm.admeo.SysPasswordPolicyLines");
    }


    /**
     * Gets the attribute value for PolicyLinesSno, using the alias name PolicyLinesSno.
     * @return the value of PolicyLinesSno
     */
    public Integer getPolicyLinesSno() {
        return (Integer) getAttributeInternal(POLICYLINESSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PolicyLinesSno.
     * @param value value to set the PolicyLinesSno
     */
    public void setPolicyLinesSno(Integer value) {
        setAttributeInternal(POLICYLINESSNO, value);
    }

    /**
     * Gets the attribute value for PolicyHeaderSno, using the alias name PolicyHeaderSno.
     * @return the value of PolicyHeaderSno
     */
    public Integer getPolicyHeaderSno() {
        return (Integer) getAttributeInternal(POLICYHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PolicyHeaderSno.
     * @param value value to set the PolicyHeaderSno
     */
    public void setPolicyHeaderSno(Integer value) {
        setAttributeInternal(POLICYHEADERSNO, value);
    }

    /**
     * Gets the attribute value for PasswordParameterSno, using the alias name PasswordParameterSno.
     * @return the value of PasswordParameterSno
     */
    public Integer getPasswordParameterSno() {
        return (Integer) getAttributeInternal(PASSWORDPARAMETERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PasswordParameterSno.
     * @param value value to set the PasswordParameterSno
     */
    public void setPasswordParameterSno(Integer value) {
        setAttributeInternal(PASSWORDPARAMETERSNO, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * @return the associated entity SysPasswordPolicyHeaderImpl.
     */
    public SysPasswordPolicyHeaderImpl getSysPasswordPolicyHeader() {
        return (SysPasswordPolicyHeaderImpl) getAttributeInternal(SYSPASSWORDPOLICYHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity SysPasswordPolicyHeaderImpl.
     */
    public void setSysPasswordPolicyHeader(SysPasswordPolicyHeaderImpl value) {
        setAttributeInternal(SYSPASSWORDPOLICYHEADER, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getSysPasswordParameter() {
        return (EntityImpl) getAttributeInternal(SYSPASSWORDPARAMETER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setSysPasswordParameter(EntityImpl value) {
        setAttributeInternal(SYSPASSWORDPARAMETER, value);
    }


    /**
     * @param policyLinesSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer policyLinesSno) {
        return new Key(new Object[] { policyLinesSno });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "POLICY_LINES_SNO",this.getEntityDef().getSource(), null, null);
           ApplicationModule am=getDBTransaction().getRootApplicationModule();
           ViewObject vo=am.findViewObject("SysPasswordPolicyHeaderCRUD");
           
           populateAttributeAsChanged(POLICYLINESSNO, Integer.parseInt(result));
            populateAttributeAsChanged(POLICYHEADERSNO, vo.getCurrentRow().getAttribute("PolicyHeaderSno"));
        }        
        super.doDML(operation, e);
    }
}

