package erpadm.modeladm.admeo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 17:54:23 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysUsersModuleImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        ModuleAction,
        IsAllow,
        AllowAdd,
        AllowDelete,
        AllowEdit,
        AllowSupervise,
        ViewScanFile,
        ScanFile,
        AllowCancel,
        AllowEditOther,
        AllowPrint,
        AllowUnsupervise,
        Remarks,
        AccessType,
        IsActive,
        UsersModuleSno,
        LastUpdatedDate,
        CreatedBy,
        LastUpdatedBy,
        CreatedDate,
        ModuleId,
        SysModuleDetail,
        SysUsers,
        SysUsersModuleCompany;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERID = AttributesEnum.UserId.index();
    public static final int MODULEACTION = AttributesEnum.ModuleAction.index();
    public static final int ISALLOW = AttributesEnum.IsAllow.index();
    public static final int ALLOWADD = AttributesEnum.AllowAdd.index();
    public static final int ALLOWDELETE = AttributesEnum.AllowDelete.index();
    public static final int ALLOWEDIT = AttributesEnum.AllowEdit.index();
    public static final int ALLOWSUPERVISE = AttributesEnum.AllowSupervise.index();
    public static final int VIEWSCANFILE = AttributesEnum.ViewScanFile.index();
    public static final int SCANFILE = AttributesEnum.ScanFile.index();
    public static final int ALLOWCANCEL = AttributesEnum.AllowCancel.index();
    public static final int ALLOWEDITOTHER = AttributesEnum.AllowEditOther.index();
    public static final int ALLOWPRINT = AttributesEnum.AllowPrint.index();
    public static final int ALLOWUNSUPERVISE = AttributesEnum.AllowUnsupervise.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ACCESSTYPE = AttributesEnum.AccessType.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int USERSMODULESNO = AttributesEnum.UsersModuleSno.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODULEID = AttributesEnum.ModuleId.index();
    public static final int SYSMODULEDETAIL = AttributesEnum.SysModuleDetail.index();
    public static final int SYSUSERS = AttributesEnum.SysUsers.index();
    public static final int SYSUSERSMODULECOMPANY = AttributesEnum.SysUsersModuleCompany.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysUsersModuleImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpadm.modeladm.admeo.SysUsersModule");
    }


    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(Integer value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for ModuleAction, using the alias name ModuleAction.
     * @return the value of ModuleAction
     */
    public String getModuleAction() {
        return (String) getAttributeInternal(MODULEACTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModuleAction.
     * @param value value to set the ModuleAction
     */
    public void setModuleAction(String value) {
        setAttributeInternal(MODULEACTION, value);
    }

    /**
     * Gets the attribute value for IsAllow, using the alias name IsAllow.
     * @return the value of IsAllow
     */
    public String getIsAllow() {
        return (String) getAttributeInternal(ISALLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsAllow.
     * @param value value to set the IsAllow
     */
    public void setIsAllow(String value) {
        setAttributeInternal(ISALLOW, value);
    }

    /**
     * Gets the attribute value for AllowAdd, using the alias name AllowAdd.
     * @return the value of AllowAdd
     */
    public String getAllowAdd() {
        return (String) getAttributeInternal(ALLOWADD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowAdd.
     * @param value value to set the AllowAdd
     */
    public void setAllowAdd(String value) {
        setAttributeInternal(ALLOWADD, value);
    }

    /**
     * Gets the attribute value for AllowDelete, using the alias name AllowDelete.
     * @return the value of AllowDelete
     */
    public String getAllowDelete() {
        return (String) getAttributeInternal(ALLOWDELETE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowDelete.
     * @param value value to set the AllowDelete
     */
    public void setAllowDelete(String value) {
        setAttributeInternal(ALLOWDELETE, value);
    }

    /**
     * Gets the attribute value for AllowEdit, using the alias name AllowEdit.
     * @return the value of AllowEdit
     */
    public String getAllowEdit() {
        return (String) getAttributeInternal(ALLOWEDIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowEdit.
     * @param value value to set the AllowEdit
     */
    public void setAllowEdit(String value) {
        setAttributeInternal(ALLOWEDIT, value);
    }

    /**
     * Gets the attribute value for AllowSupervise, using the alias name AllowSupervise.
     * @return the value of AllowSupervise
     */
    public String getAllowSupervise() {
        return (String) getAttributeInternal(ALLOWSUPERVISE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowSupervise.
     * @param value value to set the AllowSupervise
     */
    public void setAllowSupervise(String value) {
        setAttributeInternal(ALLOWSUPERVISE, value);
    }

    /**
     * Gets the attribute value for ViewScanFile, using the alias name ViewScanFile.
     * @return the value of ViewScanFile
     */
    public String getViewScanFile() {
        return (String) getAttributeInternal(VIEWSCANFILE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ViewScanFile.
     * @param value value to set the ViewScanFile
     */
    public void setViewScanFile(String value) {
        setAttributeInternal(VIEWSCANFILE, value);
    }

    /**
     * Gets the attribute value for ScanFile, using the alias name ScanFile.
     * @return the value of ScanFile
     */
    public String getScanFile() {
        return (String) getAttributeInternal(SCANFILE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScanFile.
     * @param value value to set the ScanFile
     */
    public void setScanFile(String value) {
        setAttributeInternal(SCANFILE, value);
    }

    /**
     * Gets the attribute value for AllowCancel, using the alias name AllowCancel.
     * @return the value of AllowCancel
     */
    public String getAllowCancel() {
        return (String) getAttributeInternal(ALLOWCANCEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowCancel.
     * @param value value to set the AllowCancel
     */
    public void setAllowCancel(String value) {
        setAttributeInternal(ALLOWCANCEL, value);
    }

    /**
     * Gets the attribute value for AllowEditOther, using the alias name AllowEditOther.
     * @return the value of AllowEditOther
     */
    public String getAllowEditOther() {
        return (String) getAttributeInternal(ALLOWEDITOTHER);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowEditOther.
     * @param value value to set the AllowEditOther
     */
    public void setAllowEditOther(String value) {
        setAttributeInternal(ALLOWEDITOTHER, value);
    }

    /**
     * Gets the attribute value for AllowPrint, using the alias name AllowPrint.
     * @return the value of AllowPrint
     */
    public String getAllowPrint() {
        return (String) getAttributeInternal(ALLOWPRINT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowPrint.
     * @param value value to set the AllowPrint
     */
    public void setAllowPrint(String value) {
        setAttributeInternal(ALLOWPRINT, value);
    }

    /**
     * Gets the attribute value for AllowUnsupervise, using the alias name AllowUnsupervise.
     * @return the value of AllowUnsupervise
     */
    public String getAllowUnsupervise() {
        return (String) getAttributeInternal(ALLOWUNSUPERVISE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowUnsupervise.
     * @param value value to set the AllowUnsupervise
     */
    public void setAllowUnsupervise(String value) {
        setAttributeInternal(ALLOWUNSUPERVISE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for AccessType, using the alias name AccessType.
     * @return the value of AccessType
     */
    public String getAccessType() {
        return (String) getAttributeInternal(ACCESSTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccessType.
     * @param value value to set the AccessType
     */
    public void setAccessType(String value) {
        setAttributeInternal(ACCESSTYPE, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for UsersModuleSno, using the alias name UsersModuleSno.
     * @return the value of UsersModuleSno
     */
    public Integer getUsersModuleSno() {
        return (Integer) getAttributeInternal(USERSMODULESNO);
    }


    /**
     * Sets <code>value</code> as the attribute value for UsersModuleSno.
     * @param value value to set the UsersModuleSno
     */
    public void setUsersModuleSno(Integer value) {
        setAttributeInternal(USERSMODULESNO, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModuleId, using the alias name ModuleId.
     * @return the value of ModuleId
     */
    public String getModuleId() {
        return (String) getAttributeInternal(MODULEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModuleId.
     * @param value value to set the ModuleId
     */
    public void setModuleId(String value) {
        setAttributeInternal(MODULEID, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getSysModuleDetail() {
        return (EntityImpl) getAttributeInternal(SYSMODULEDETAIL);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setSysModuleDetail(EntityImpl value) {
        setAttributeInternal(SYSMODULEDETAIL, value);
    }

    /**
     * @return the associated entity SysUsersImpl.
     */
    public SysUsersImpl getSysUsers() {
        return (SysUsersImpl) getAttributeInternal(SYSUSERS);
    }

    /**
     * Sets <code>value</code> as the associated entity SysUsersImpl.
     */
    public void setSysUsers(SysUsersImpl value) {
        setAttributeInternal(SYSUSERS, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSysUsersModuleCompany() {
        return (RowIterator) getAttributeInternal(SYSUSERSMODULECOMPANY);
    }


    /**
     * @param usersModuleSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer usersModuleSno) {
        return new Key(new Object[] { usersModuleSno });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "USERS_MODULE_SNO",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(USERSMODULESNO, Integer.parseInt(result));
        }  
        super.doDML(operation, e);
    }

    
}

