package erpadm.modeladm.admvo;


import erpadm.modeladm.admeo.AdminCompanyImpl;
import erpadm.modeladm.admeo.AdminCompanyTypeImpl;
import erpadm.modeladm.admvo.common.AdminCompanyVORow;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 17 13:33:18 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminCompanyVORowImpl extends ViewRowImpl implements AdminCompanyVORow {


    public static final int ENTITY_ADMINCOMPANY = 0;
    public static final int ENTITY_ADMINCOMPANYTYPE = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CompCode,
        CompanyName,
        Address,
        Gstno,
        Ntnno,
        Phone,
        Fax,
        CountryId,
        CityId,
        Active,
        ParentCompCode,
        CompanyTypeSno,
        ContactPerson,
        CompanyShortName,
        CompanyShortCode,
        MobileNo,
        CurrencySno,
        txtCountryName,
        txtCityName,
        RegistrationNo,
        BusinessStartDate,
        Website,
        Email,
        GlobalCompCode,
        txtParentCompShortCode,
        txtParentCompanyShortName,
        txtParentCompanyName,
        txtChildCompanyName,
        txtChildCompanyCode,
        txtSelected,
        txtCountCompany,
        CreatedDate,
        CreatedBy,
        LastUpdatedBy,
        LastUpdatedDate,
        txtParentParentCompanyCode,
        txtCompanyTypeName,
        txtParentCompanyCode,
        txtNextCompanyTypeSno,
        txtCountNextCompanyType,
        txtCurrentTypeLevel,
        txtCurrentGroupSno,
        txtParentCompanyTypeSno,
        CompanyHierarchyPath,
        txtParentHierarchyPath,
        CompanyTypeSnoMast,
        CompanyTypeName,
        TypeLevel,
        AdminBranchesVO,
        ParentCompCodeAdminCompanyVO,
        AdminCompanyVO,
        SysActionGroupCompanyVO,
        SysActionGroupLinesCompanyVO,
        SysUsersModuleCompanyVO,
        SysUserCompanyVO,
        TempAdminCompanyAccessVO,
        AdminCompanyTypeVO,
        TempAdminDepartmentAccessVO,
        AccAdminCompanyTypeVO,
        AccSetCurrency,
        AccSmCountryVO,
        AccSmCityVO,
        AccAdminParentCompanyQVO,
        AccAdminCompanyVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPCODE = AttributesEnum.CompCode.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int GSTNO = AttributesEnum.Gstno.index();
    public static final int NTNNO = AttributesEnum.Ntnno.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int FAX = AttributesEnum.Fax.index();
    public static final int COUNTRYID = AttributesEnum.CountryId.index();
    public static final int CITYID = AttributesEnum.CityId.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int PARENTCOMPCODE = AttributesEnum.ParentCompCode.index();
    public static final int COMPANYTYPESNO = AttributesEnum.CompanyTypeSno.index();
    public static final int CONTACTPERSON = AttributesEnum.ContactPerson.index();
    public static final int COMPANYSHORTNAME = AttributesEnum.CompanyShortName.index();
    public static final int COMPANYSHORTCODE = AttributesEnum.CompanyShortCode.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int CURRENCYSNO = AttributesEnum.CurrencySno.index();
    public static final int TXTCOUNTRYNAME = AttributesEnum.txtCountryName.index();
    public static final int TXTCITYNAME = AttributesEnum.txtCityName.index();
    public static final int REGISTRATIONNO = AttributesEnum.RegistrationNo.index();
    public static final int BUSINESSSTARTDATE = AttributesEnum.BusinessStartDate.index();
    public static final int WEBSITE = AttributesEnum.Website.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int GLOBALCOMPCODE = AttributesEnum.GlobalCompCode.index();
    public static final int TXTPARENTCOMPSHORTCODE = AttributesEnum.txtParentCompShortCode.index();
    public static final int TXTPARENTCOMPANYSHORTNAME = AttributesEnum.txtParentCompanyShortName.index();
    public static final int TXTPARENTCOMPANYNAME = AttributesEnum.txtParentCompanyName.index();
    public static final int TXTCHILDCOMPANYNAME = AttributesEnum.txtChildCompanyName.index();
    public static final int TXTCHILDCOMPANYCODE = AttributesEnum.txtChildCompanyCode.index();
    public static final int TXTSELECTED = AttributesEnum.txtSelected.index();
    public static final int TXTCOUNTCOMPANY = AttributesEnum.txtCountCompany.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TXTPARENTPARENTCOMPANYCODE = AttributesEnum.txtParentParentCompanyCode.index();
    public static final int TXTCOMPANYTYPENAME = AttributesEnum.txtCompanyTypeName.index();
    public static final int TXTPARENTCOMPANYCODE = AttributesEnum.txtParentCompanyCode.index();
    public static final int TXTNEXTCOMPANYTYPESNO = AttributesEnum.txtNextCompanyTypeSno.index();
    public static final int TXTCOUNTNEXTCOMPANYTYPE = AttributesEnum.txtCountNextCompanyType.index();
    public static final int TXTCURRENTTYPELEVEL = AttributesEnum.txtCurrentTypeLevel.index();
    public static final int TXTCURRENTGROUPSNO = AttributesEnum.txtCurrentGroupSno.index();
    public static final int TXTPARENTCOMPANYTYPESNO = AttributesEnum.txtParentCompanyTypeSno.index();
    public static final int COMPANYHIERARCHYPATH = AttributesEnum.CompanyHierarchyPath.index();
    public static final int TXTPARENTHIERARCHYPATH = AttributesEnum.txtParentHierarchyPath.index();
    public static final int COMPANYTYPESNOMAST = AttributesEnum.CompanyTypeSnoMast.index();
    public static final int COMPANYTYPENAME = AttributesEnum.CompanyTypeName.index();
    public static final int TYPELEVEL = AttributesEnum.TypeLevel.index();
    public static final int ADMINBRANCHESVO = AttributesEnum.AdminBranchesVO.index();
    public static final int PARENTCOMPCODEADMINCOMPANYVO = AttributesEnum.ParentCompCodeAdminCompanyVO.index();
    public static final int ADMINCOMPANYVO = AttributesEnum.AdminCompanyVO.index();
    public static final int SYSACTIONGROUPCOMPANYVO = AttributesEnum.SysActionGroupCompanyVO.index();
    public static final int SYSACTIONGROUPLINESCOMPANYVO = AttributesEnum.SysActionGroupLinesCompanyVO.index();
    public static final int SYSUSERSMODULECOMPANYVO = AttributesEnum.SysUsersModuleCompanyVO.index();
    public static final int SYSUSERCOMPANYVO = AttributesEnum.SysUserCompanyVO.index();
    public static final int TEMPADMINCOMPANYACCESSVO = AttributesEnum.TempAdminCompanyAccessVO.index();
    public static final int ADMINCOMPANYTYPEVO = AttributesEnum.AdminCompanyTypeVO.index();
    public static final int TEMPADMINDEPARTMENTACCESSVO = AttributesEnum.TempAdminDepartmentAccessVO.index();
    public static final int ACCADMINCOMPANYTYPEVO = AttributesEnum.AccAdminCompanyTypeVO.index();
    public static final int ACCSETCURRENCY = AttributesEnum.AccSetCurrency.index();
    public static final int ACCSMCOUNTRYVO = AttributesEnum.AccSmCountryVO.index();
    public static final int ACCSMCITYVO = AttributesEnum.AccSmCityVO.index();
    public static final int ACCADMINPARENTCOMPANYQVO = AttributesEnum.AccAdminParentCompanyQVO.index();
    public static final int ACCADMINCOMPANYVO = AttributesEnum.AccAdminCompanyVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AdminCompanyVORowImpl() {
    }

    /**
     * Gets AdminCompany entity object.
     * @return the AdminCompany
     */
    public AdminCompanyImpl getAdminCompany() {
        return (AdminCompanyImpl) getEntity(ENTITY_ADMINCOMPANY);
    }

    /**
     * Gets AdminCompanyType entity object.
     * @return the AdminCompanyType
     */
    public AdminCompanyTypeImpl getAdminCompanyType() {
        return (AdminCompanyTypeImpl) getEntity(ENTITY_ADMINCOMPANYTYPE);
    }

    /**
     * Gets the attribute value for COMP_CODE using the alias name CompCode.
     * @return the COMP_CODE
     */
    public BigDecimal getCompCode() {
        return (BigDecimal) getAttributeInternal(COMPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMP_CODE using the alias name CompCode.
     * @param value value to set the COMP_CODE
     */
    public void setCompCode(BigDecimal value) {
        setAttributeInternal(COMPCODE, value);
    }

    /**
     * Gets the attribute value for COMPANY_NAME using the alias name CompanyName.
     * @return the COMPANY_NAME
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName.
     * @param value value to set the COMPANY_NAME
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for ADDRESS using the alias name Address.
     * @return the ADDRESS
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS using the alias name Address.
     * @param value value to set the ADDRESS
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for GSTNO using the alias name Gstno.
     * @return the GSTNO
     */
    public String getGstno() {
        return (String) getAttributeInternal(GSTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GSTNO using the alias name Gstno.
     * @param value value to set the GSTNO
     */
    public void setGstno(String value) {
        setAttributeInternal(GSTNO, value);
    }

    /**
     * Gets the attribute value for NTNNO using the alias name Ntnno.
     * @return the NTNNO
     */
    public String getNtnno() {
        return (String) getAttributeInternal(NTNNO);
    }

    /**
     * Sets <code>value</code> as attribute value for NTNNO using the alias name Ntnno.
     * @param value value to set the NTNNO
     */
    public void setNtnno(String value) {
        setAttributeInternal(NTNNO, value);
    }

    /**
     * Gets the attribute value for PHONE using the alias name Phone.
     * @return the PHONE
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE using the alias name Phone.
     * @param value value to set the PHONE
     */
    public void setPhone(String value) {
        setAttributeInternal(PHONE, value);
    }

    /**
     * Gets the attribute value for FAX using the alias name Fax.
     * @return the FAX
     */
    public String getFax() {
        return (String) getAttributeInternal(FAX);
    }

    /**
     * Sets <code>value</code> as attribute value for FAX using the alias name Fax.
     * @param value value to set the FAX
     */
    public void setFax(String value) {
        setAttributeInternal(FAX, value);
    }

    /**
     * Gets the attribute value for COUNTRY_ID using the alias name CountryId.
     * @return the COUNTRY_ID
     */
    public Integer getCountryId() {
        return (Integer) getAttributeInternal(COUNTRYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_ID using the alias name CountryId.
     * @param value value to set the COUNTRY_ID
     */
    public void setCountryId(Integer value) {
        setAttributeInternal(COUNTRYID, value);
    }

    /**
     * Gets the attribute value for CITY_ID using the alias name CityId.
     * @return the CITY_ID
     */
    public String getCityId() {
        return (String) getAttributeInternal(CITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_ID using the alias name CityId.
     * @param value value to set the CITY_ID
     */
    public void setCityId(String value) {
        setAttributeInternal(CITYID, value);
    }

    /**
     * Gets the attribute value for ACTIVE using the alias name Active.
     * @return the ACTIVE
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE using the alias name Active.
     * @param value value to set the ACTIVE
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for PARENT_COMP_CODE using the alias name ParentCompCode.
     * @return the PARENT_COMP_CODE
     */
    public Integer getParentCompCode() {
        return (Integer) getAttributeInternal(PARENTCOMPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_COMP_CODE using the alias name ParentCompCode.
     * @param value value to set the PARENT_COMP_CODE
     */
    public void setParentCompCode(Integer value) {
        setAttributeInternal(PARENTCOMPCODE, value);
    }

    /**
     * Gets the attribute value for COMPANY_TYPE_SNO using the alias name CompanyTypeSno.
     * @return the COMPANY_TYPE_SNO
     */
    public Integer getCompanyTypeSno() {
        return (Integer) getAttributeInternal(COMPANYTYPESNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_TYPE_SNO using the alias name CompanyTypeSno.
     * @param value value to set the COMPANY_TYPE_SNO
     */
    public void setCompanyTypeSno(Integer value) {
        setAttributeInternal(COMPANYTYPESNO, value);
        setParentCompCode(0);
    }

    /**
     * Gets the attribute value for CONTACT_PERSON using the alias name ContactPerson.
     * @return the CONTACT_PERSON
     */
    public String getContactPerson() {
        return (String) getAttributeInternal(CONTACTPERSON);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_PERSON using the alias name ContactPerson.
     * @param value value to set the CONTACT_PERSON
     */
    public void setContactPerson(String value) {
        setAttributeInternal(CONTACTPERSON, value);
    }

    /**
     * Gets the attribute value for COMPANY_SHORT_NAME using the alias name CompanyShortName.
     * @return the COMPANY_SHORT_NAME
     */
    public String getCompanyShortName() {
        return (String) getAttributeInternal(COMPANYSHORTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_SHORT_NAME using the alias name CompanyShortName.
     * @param value value to set the COMPANY_SHORT_NAME
     */
    public void setCompanyShortName(String value) {
        setAttributeInternal(COMPANYSHORTNAME, value);
    }

    /**
     * Gets the attribute value for COMPANY_SHORT_CODE using the alias name CompanyShortCode.
     * @return the COMPANY_SHORT_CODE
     */
    public Integer getCompanyShortCode() {
        return (Integer) getAttributeInternal(COMPANYSHORTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_SHORT_CODE using the alias name CompanyShortCode.
     * @param value value to set the COMPANY_SHORT_CODE
     */
    public void setCompanyShortCode(Integer value) {
        setAttributeInternal(COMPANYSHORTCODE, value);
    }

    /**
     * Gets the attribute value for MOBILE_NO using the alias name MobileNo.
     * @return the MOBILE_NO
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_NO using the alias name MobileNo.
     * @param value value to set the MOBILE_NO
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for CURRENCY_SNO using the alias name CurrencySno.
     * @return the CURRENCY_SNO
     */
    public Integer getCurrencySno() {
        return (Integer) getAttributeInternal(CURRENCYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_SNO using the alias name CurrencySno.
     * @param value value to set the CURRENCY_SNO
     */
    public void setCurrencySno(Integer value) {
        setAttributeInternal(CURRENCYSNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCountryName.
     * @return the txtCountryName
     */
    public String gettxtCountryName() {
        return (String) getAttributeInternal(TXTCOUNTRYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCountryName.
     * @param value value to set the  txtCountryName
     */
    public void settxtCountryName(String value) {
        setAttributeInternal(TXTCOUNTRYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCityName.
     * @return the txtCityName
     */
    public String gettxtCityName() {
        return (String) getAttributeInternal(TXTCITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCityName.
     * @param value value to set the  txtCityName
     */
    public void settxtCityName(String value) {
        setAttributeInternal(TXTCITYNAME, value);
    }

    /**
     * Gets the attribute value for REGISTRATION_NO using the alias name RegistrationNo.
     * @return the REGISTRATION_NO
     */
    public String getRegistrationNo() {
        return (String) getAttributeInternal(REGISTRATIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REGISTRATION_NO using the alias name RegistrationNo.
     * @param value value to set the REGISTRATION_NO
     */
    public void setRegistrationNo(String value) {
        setAttributeInternal(REGISTRATIONNO, value);
    }

    /**
     * Gets the attribute value for BUSINESS_START_DATE using the alias name BusinessStartDate.
     * @return the BUSINESS_START_DATE
     */
    public Timestamp getBusinessStartDate() {
        return (Timestamp) getAttributeInternal(BUSINESSSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_START_DATE using the alias name BusinessStartDate.
     * @param value value to set the BUSINESS_START_DATE
     */
    public void setBusinessStartDate(Timestamp value) {
        setAttributeInternal(BUSINESSSTARTDATE, value);
    }

    /**
     * Gets the attribute value for WEBSITE using the alias name Website.
     * @return the WEBSITE
     */
    public String getWebsite() {
        return (String) getAttributeInternal(WEBSITE);
    }

    /**
     * Sets <code>value</code> as attribute value for WEBSITE using the alias name Website.
     * @param value value to set the WEBSITE
     */
    public void setWebsite(String value) {
        setAttributeInternal(WEBSITE, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for GLOBAL_COMP_CODE using the alias name GlobalCompCode.
     * @return the GLOBAL_COMP_CODE
     */
    public Long getGlobalCompCode() {
        return (Long) getAttributeInternal(GLOBALCOMPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLOBAL_COMP_CODE using the alias name GlobalCompCode.
     * @param value value to set the GLOBAL_COMP_CODE
     */
    public void setGlobalCompCode(Long value) {
        setAttributeInternal(GLOBALCOMPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtParentCompShortCode.
     * @return the txtParentCompShortCode
     */
    public Integer gettxtParentCompShortCode() {
        return (Integer) getAttributeInternal(TXTPARENTCOMPSHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtParentCompShortCode.
     * @param value value to set the  txtParentCompShortCode
     */
    public void settxtParentCompShortCode(Integer value) {
        setAttributeInternal(TXTPARENTCOMPSHORTCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtParentCompanyShortName.
     * @return the txtParentCompanyShortName
     */
    public String gettxtParentCompanyShortName() {
        return (String) getAttributeInternal(TXTPARENTCOMPANYSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtParentCompanyShortName.
     * @param value value to set the  txtParentCompanyShortName
     */
    public void settxtParentCompanyShortName(String value) {
        setAttributeInternal(TXTPARENTCOMPANYSHORTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtParentCompanyName.
     * @return the txtParentCompanyName
     */
    public String gettxtParentCompanyName() {
        return (String) getAttributeInternal(TXTPARENTCOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtParentCompanyName.
     * @param value value to set the  txtParentCompanyName
     */
    public void settxtParentCompanyName(String value) {
        setAttributeInternal(TXTPARENTCOMPANYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtChildCompanyName.
     * @return the txtChildCompanyName
     */
    public String gettxtChildCompanyName() {
        return (String) getAttributeInternal(TXTCHILDCOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtChildCompanyName.
     * @param value value to set the  txtChildCompanyName
     */
    public void settxtChildCompanyName(String value) {
        setAttributeInternal(TXTCHILDCOMPANYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtChildCompanyCode.
     * @return the txtChildCompanyCode
     */
    public Integer gettxtChildCompanyCode() {
        return (Integer) getAttributeInternal(TXTCHILDCOMPANYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtChildCompanyCode.
     * @param value value to set the  txtChildCompanyCode
     */
    public void settxtChildCompanyCode(Integer value) {
        setAttributeInternal(TXTCHILDCOMPANYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSelected.
     * @return the txtSelected
     */
    public String gettxtSelected() {
        return (String) getAttributeInternal(TXTSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSelected.
     * @param value value to set the  txtSelected
     */
    public void settxtSelected(String value) {
        setAttributeInternal(TXTSELECTED, value);
    }


    /**
     * Gets the attribute value for the calculated attribute txtCountCompany.
     * @return the txtCountCompany
     */
    public Integer gettxtCountCompany() {
        return (Integer) getAttributeInternal(TXTCOUNTCOMPANY);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtParentParentCompanyCode.
     * @return the txtParentParentCompanyCode
     */
    public Integer gettxtParentParentCompanyCode() {
        return (Integer) getAttributeInternal(TXTPARENTPARENTCOMPANYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtParentParentCompanyCode.
     * @param value value to set the  txtParentParentCompanyCode
     */
    public void settxtParentParentCompanyCode(Integer value) {
        setAttributeInternal(TXTPARENTPARENTCOMPANYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCompanyTypeName.
     * @return the txtCompanyTypeName
     */
    public String gettxtCompanyTypeName() {
        return (String) getAttributeInternal(TXTCOMPANYTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCompanyTypeName.
     * @param value value to set the  txtCompanyTypeName
     */
    public void settxtCompanyTypeName(String value) {
        setAttributeInternal(TXTCOMPANYTYPENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtParentCompanyCode.
     * @return the txtParentCompanyCode
     */
    public Integer gettxtParentCompanyCode() {
        return (Integer) getAttributeInternal(TXTPARENTCOMPANYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtParentCompanyCode.
     * @param value value to set the  txtParentCompanyCode
     */
    public void settxtParentCompanyCode(Integer value) {
        setAttributeInternal(TXTPARENTCOMPANYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtNextCompanyTypeSno.
     * @return the txtNextCompanyTypeSno
     */
    public Integer gettxtNextCompanyTypeSno() {
        return (Integer) getAttributeInternal(TXTNEXTCOMPANYTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtNextCompanyTypeSno.
     * @param value value to set the  txtNextCompanyTypeSno
     */
    public void settxtNextCompanyTypeSno(Integer value) {
        setAttributeInternal(TXTNEXTCOMPANYTYPESNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCountNextCompanyType.
     * @return the txtCountNextCompanyType
     */
    public Integer gettxtCountNextCompanyType() {
        return (Integer) getAttributeInternal(TXTCOUNTNEXTCOMPANYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCountNextCompanyType.
     * @param value value to set the  txtCountNextCompanyType
     */
    public void settxtCountNextCompanyType(Integer value) {
        setAttributeInternal(TXTCOUNTNEXTCOMPANYTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCurrentTypeLevel.
     * @return the txtCurrentTypeLevel
     */
    public Integer gettxtCurrentTypeLevel() {
        return (Integer) getAttributeInternal(TXTCURRENTTYPELEVEL);
    }


    /**
     * Gets the attribute value for the calculated attribute txtCurrentGroupSno.
     * @return the txtCurrentGroupSno
     */
    public Integer gettxtCurrentGroupSno() {
        return (Integer) getAttributeInternal(TXTCURRENTGROUPSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCurrentGroupSno.
     * @param value value to set the  txtCurrentGroupSno
     */
    public void settxtCurrentGroupSno(Integer value) {
        setAttributeInternal(TXTCURRENTGROUPSNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtParentCompanyTypeSno.
     * @return the txtParentCompanyTypeSno
     */
    public Integer gettxtParentCompanyTypeSno() {
        return (Integer) getAttributeInternal(TXTPARENTCOMPANYTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtParentCompanyTypeSno.
     * @param value value to set the  txtParentCompanyTypeSno
     */
    public void settxtParentCompanyTypeSno(Integer value) {
        setAttributeInternal(TXTPARENTCOMPANYTYPESNO, value);
    }

    /**
     * Gets the attribute value for COMPANY_HIERARCHY_PATH using the alias name CompanyHierarchyPath.
     * @return the COMPANY_HIERARCHY_PATH
     */
    public String getCompanyHierarchyPath() {
        return (String) getAttributeInternal(COMPANYHIERARCHYPATH);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_HIERARCHY_PATH using the alias name CompanyHierarchyPath.
     * @param value value to set the COMPANY_HIERARCHY_PATH
     */
    public void setCompanyHierarchyPath(String value) {
        setAttributeInternal(COMPANYHIERARCHYPATH, value);
    }

    /**
     * Gets the attribute value for TXT_PARENT_HIERARCHY_PATH using the alias name txtParentHierarchyPath.
     * @return the TXT_PARENT_HIERARCHY_PATH
     */
    public String gettxtParentHierarchyPath() {
        return (String) getAttributeInternal(TXTPARENTHIERARCHYPATH);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PARENT_HIERARCHY_PATH using the alias name txtParentHierarchyPath.
     * @param value value to set the TXT_PARENT_HIERARCHY_PATH
     */
    public void settxtParentHierarchyPath(String value) {
        setAttributeInternal(TXTPARENTHIERARCHYPATH, value);
    }

    /**
     * Gets the attribute value for COMPANY_TYPE_SNO using the alias name CompanyTypeSnoMast.
     * @return the COMPANY_TYPE_SNO
     */
    public Integer getCompanyTypeSnoMast() {
        return (Integer) getAttributeInternal(COMPANYTYPESNOMAST);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_TYPE_SNO using the alias name CompanyTypeSnoMast.
     * @param value value to set the COMPANY_TYPE_SNO
     */
    public void setCompanyTypeSnoMast(Integer value) {
        setAttributeInternal(COMPANYTYPESNOMAST, value);
    }

    /**
     * Gets the attribute value for COMPANY_TYPE_NAME using the alias name CompanyTypeName.
     * @return the COMPANY_TYPE_NAME
     */
    public String getCompanyTypeName() {
        return (String) getAttributeInternal(COMPANYTYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_TYPE_NAME using the alias name CompanyTypeName.
     * @param value value to set the COMPANY_TYPE_NAME
     */
    public void setCompanyTypeName(String value) {
        setAttributeInternal(COMPANYTYPENAME, value);
    }


    /**
     * Gets the attribute value for TYPE_LEVEL using the alias name TypeLevel.
     * @return the TYPE_LEVEL
     */
    public Integer getTypeLevel() {
        return (Integer) getAttributeInternal(TYPELEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE_LEVEL using the alias name TypeLevel.
     * @param value value to set the TYPE_LEVEL
     */
    public void setTypeLevel(Integer value) {
        setAttributeInternal(TYPELEVEL, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AdminBranchesVO.
     */
    public RowIterator getAdminBranchesVO() {
        return (RowIterator) getAttributeInternal(ADMINBRANCHESVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ParentCompCodeAdminCompanyVO.
     */
    public Row getParentCompCodeAdminCompanyVO() {
        return (Row) getAttributeInternal(PARENTCOMPCODEADMINCOMPANYVO);
    }

    /**
     * Sets the master-detail link ParentCompCodeAdminCompanyVO between this object and <code>value</code>.
     */
    public void setParentCompCodeAdminCompanyVO(Row value) {
        setAttributeInternal(PARENTCOMPCODEADMINCOMPANYVO, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AdminCompanyVO.
     */
    public RowIterator getAdminCompanyVO() {
        return (RowIterator) getAttributeInternal(ADMINCOMPANYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupCompanyVO.
     */
    public RowIterator getSysActionGroupCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPCOMPANYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupLinesCompanyVO.
     */
    public RowIterator getSysActionGroupLinesCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPLINESCOMPANYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysUsersModuleCompanyVO.
     */
    public RowIterator getSysUsersModuleCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSUSERSMODULECOMPANYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysUserCompanyVO.
     */
    public RowIterator getSysUserCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSUSERCOMPANYVO);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TempAdminCompanyAccessVO.
     */
    public RowIterator getTempAdminCompanyAccessVO() {
        return (RowIterator) getAttributeInternal(TEMPADMINCOMPANYACCESSVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyTypeVO.
     */
    public Row getAdminCompanyTypeVO() {
        return (Row) getAttributeInternal(ADMINCOMPANYTYPEVO);
    }

    /**
     * Sets the master-detail link AdminCompanyTypeVO between this object and <code>value</code>.
     */
    public void setAdminCompanyTypeVO(Row value) {
        setAttributeInternal(ADMINCOMPANYTYPEVO, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TempAdminDepartmentAccessVO.
     */
    public RowIterator getTempAdminDepartmentAccessVO() {
        return (RowIterator) getAttributeInternal(TEMPADMINDEPARTMENTACCESSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyTypeVO.
     */
    public RowSet getAccAdminCompanyTypeVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYTYPEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSetCurrency.
     */
    public RowSet getAccSetCurrency() {
        return (RowSet) getAttributeInternal(ACCSETCURRENCY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSmCountryVO.
     */
    public RowSet getAccSmCountryVO() {
        return (RowSet) getAttributeInternal(ACCSMCOUNTRYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSmCityVO.
     */
    public RowSet getAccSmCityVO() {
        return (RowSet) getAttributeInternal(ACCSMCITYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminParentCompanyQVO.
     */
    public RowSet getAccAdminParentCompanyQVO() {
        return (RowSet) getAttributeInternal(ACCADMINPARENTCOMPANYQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyVO.
     */
    public RowSet getAccAdminCompanyVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYVO);
    }

    public void doAssigERPOneCompToGrpLinAction() {
        /*when we press undo then system unset the current row here we as setting current row that is FIRST*/
        getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
        
        ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysActionGroupLinesCompanyDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("CompanyId", getCompCode().intValue());
            //cr.setAttribute("ModuleId", getModuleId());
            //cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }
 
    public void doAssignERPOneCompToGroup() {
        /*when we press undo then system unset the current row here we as setting current row that is FIRST*/
        getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
        
            ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysActionGroupCompanyDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("CompanyId", getCompCode().intValue());
            //cr.setAttribute("ModuleId", getModuleId());
            //cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }

    public void doAssignERPOneCompToUserActionLine() {
        /*when we press undo then system unset the current row here we as setting current row that is FIRST*/
        getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();

        ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysUsersModuleCompanyDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("CompanyId", getCompCode().intValue());
            //cr.setAttribute("ModuleId", getModuleId());
            //cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }  

    public void doAssignERPOneCompToUser() {
        /*when we press undo then system unset the current row here we as setting current row that is FIRST*/
        getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
        
        ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysUserCompanyDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("CompanyId", getCompCode().intValue());
            //cr.setAttribute("ModuleId", getModuleId());
            //cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    } 
    
}

