package erpadm.modeladm.admvo;

import erpadm.modeladm.admeo.AdminCompanyImpl;
import erpadm.modeladm.admeo.SysActionGroupLinesCompanyImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 01 14:53:57 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysActionGroupLinesCompanyVORowImpl extends ViewRowImpl {
    public static final int ENTITY_SYSACTIONGROUPLINESCOMPANY = 0;
    public static final int ENTITY_ADMINCOMPANY = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GroupLinesCompanySno,
        GroupHeaderSno,
        GroupLinesSno,
        CompanyId,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        GlobalCompanyId,
        CompanyName,
        CompCode,
        CompanyShortCode,
        CompanyShortName,
        txtCountGroupActionComp,
        SysActionGroupLinesVO,
        AdminCompanyVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int GROUPLINESCOMPANYSNO = AttributesEnum.GroupLinesCompanySno.index();
    public static final int GROUPHEADERSNO = AttributesEnum.GroupHeaderSno.index();
    public static final int GROUPLINESSNO = AttributesEnum.GroupLinesSno.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int COMPCODE = AttributesEnum.CompCode.index();
    public static final int COMPANYSHORTCODE = AttributesEnum.CompanyShortCode.index();
    public static final int COMPANYSHORTNAME = AttributesEnum.CompanyShortName.index();
    public static final int TXTCOUNTGROUPACTIONCOMP = AttributesEnum.txtCountGroupActionComp.index();
    public static final int SYSACTIONGROUPLINESVO = AttributesEnum.SysActionGroupLinesVO.index();
    public static final int ADMINCOMPANYVO = AttributesEnum.AdminCompanyVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysActionGroupLinesCompanyVORowImpl() {
    }

    /**
     * Gets SysActionGroupLinesCompany entity object.
     * @return the SysActionGroupLinesCompany
     */
    public SysActionGroupLinesCompanyImpl getSysActionGroupLinesCompany() {
        return (SysActionGroupLinesCompanyImpl) getEntity(ENTITY_SYSACTIONGROUPLINESCOMPANY);
    }

    /**
     * Gets AdminCompany entity object.
     * @return the AdminCompany
     */
    public AdminCompanyImpl getAdminCompany() {
        return (AdminCompanyImpl) getEntity(ENTITY_ADMINCOMPANY);
    }

    /**
     * Gets the attribute value for GROUP_LINES_COMPANY_SNO using the alias name GroupLinesCompanySno.
     * @return the GROUP_LINES_COMPANY_SNO
     */
    public Long getGroupLinesCompanySno() {
        return (Long) getAttributeInternal(GROUPLINESCOMPANYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_LINES_COMPANY_SNO using the alias name GroupLinesCompanySno.
     * @param value value to set the GROUP_LINES_COMPANY_SNO
     */
    public void setGroupLinesCompanySno(Long value) {
        setAttributeInternal(GROUPLINESCOMPANYSNO, value);
    }

    /**
     * Gets the attribute value for GROUP_HEADER_SNO using the alias name GroupHeaderSno.
     * @return the GROUP_HEADER_SNO
     */
    public Long getGroupHeaderSno() {
        return (Long) getAttributeInternal(GROUPHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_HEADER_SNO using the alias name GroupHeaderSno.
     * @param value value to set the GROUP_HEADER_SNO
     */
    public void setGroupHeaderSno(Long value) {
        setAttributeInternal(GROUPHEADERSNO, value);
    }

    /**
     * Gets the attribute value for GROUP_LINES_SNO using the alias name GroupLinesSno.
     * @return the GROUP_LINES_SNO
     */
    public Long getGroupLinesSno() {
        return (Long) getAttributeInternal(GROUPLINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_LINES_SNO using the alias name GroupLinesSno.
     * @param value value to set the GROUP_LINES_SNO
     */
    public void setGroupLinesSno(Long value) {
        setAttributeInternal(GROUPLINESSNO, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for IS_ACTIVE using the alias name IsActive.
     * @return the IS_ACTIVE
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_ACTIVE using the alias name IsActive.
     * @param value value to set the IS_ACTIVE
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @return the GLOBAL_COMPANY_ID
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @param value value to set the GLOBAL_COMPANY_ID
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for COMPANY_NAME using the alias name CompanyName.
     * @return the COMPANY_NAME
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName.
     * @param value value to set the COMPANY_NAME
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for COMP_CODE using the alias name CompCode.
     * @return the COMP_CODE
     */
    public BigDecimal getCompCode() {
        return (BigDecimal) getAttributeInternal(COMPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMP_CODE using the alias name CompCode.
     * @param value value to set the COMP_CODE
     */
    public void setCompCode(BigDecimal value) {
        setAttributeInternal(COMPCODE, value);
    }

    /**
     * Gets the attribute value for COMPANY_SHORT_CODE using the alias name CompanyShortCode.
     * @return the COMPANY_SHORT_CODE
     */
    public Integer getCompanyShortCode() {
        return (Integer) getAttributeInternal(COMPANYSHORTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_SHORT_CODE using the alias name CompanyShortCode.
     * @param value value to set the COMPANY_SHORT_CODE
     */
    public void setCompanyShortCode(Integer value) {
        setAttributeInternal(COMPANYSHORTCODE, value);
    }

    /**
     * Gets the attribute value for COMPANY_SHORT_NAME using the alias name CompanyShortName.
     * @return the COMPANY_SHORT_NAME
     */
    public String getCompanyShortName() {
        return (String) getAttributeInternal(COMPANYSHORTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_SHORT_NAME using the alias name CompanyShortName.
     * @param value value to set the COMPANY_SHORT_NAME
     */
    public void setCompanyShortName(String value) {
        setAttributeInternal(COMPANYSHORTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCountGroupActionComp.
     * @return the txtCountGroupActionComp
     */
    public Integer gettxtCountGroupActionComp() {
        return (Integer) getAttributeInternal(TXTCOUNTGROUPACTIONCOMP);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SysActionGroupLinesVO.
     */
    public Row getSysActionGroupLinesVO() {
        return (Row) getAttributeInternal(SYSACTIONGROUPLINESVO);
    }

    /**
     * Sets the master-detail link SysActionGroupLinesVO between this object and <code>value</code>.
     */
    public void setSysActionGroupLinesVO(Row value) {
        setAttributeInternal(SYSACTIONGROUPLINESVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO.
     */
    public Row getAdminCompanyVO() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO);
    }

    /**
     * Sets the master-detail link AdminCompanyVO between this object and <code>value</code>.
     */
    public void setAdminCompanyVO(Row value) {
        setAttributeInternal(ADMINCOMPANYVO, value);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getSysActionGroupLinesVO().getAttribute("txtIsSupervised").toString().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

