package erpadm.modeladm.admvo;

import erpadm.modeladm.admeo.SysActionGroupLinesImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 01 14:46:09 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysActionGroupLinesVORowImpl extends ViewRowImpl {
    public static final int ENTITY_SYSACTIONGROUPLINES = 0;
    public static final int ENTITY_SYSMODULEDETAIL = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GroupLinesSno,
        GroupHeaderSno,
        ModuleAction,
        IsAllow,
        AllowAdd,
        AllowDelete,
        AllowEdit,
        AllowSupervise,
        ViewScanFile,
        ScanFile,
        AllowUnsupervise,
        AllowCancel,
        AllowEditOther,
        AllowPrint,
        Remarks,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        txtAGLCount,
        ModuleId,
        AccessType,
        IsActive,
        ActionCategoryId,
        ModuleActionMast,
        ActionName,
        txtIsSupervised,
        SysModuleDetailVO,
        SysActionGroupHeaderVO,
        SysActionGroupLinesCompanyVO,
        AccSysActionGroupModuleQVO,
        AccSysUserAccessTypeVO,
        AccSysGeneralValueVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int GROUPLINESSNO = AttributesEnum.GroupLinesSno.index();
    public static final int GROUPHEADERSNO = AttributesEnum.GroupHeaderSno.index();
    public static final int MODULEACTION = AttributesEnum.ModuleAction.index();
    public static final int ISALLOW = AttributesEnum.IsAllow.index();
    public static final int ALLOWADD = AttributesEnum.AllowAdd.index();
    public static final int ALLOWDELETE = AttributesEnum.AllowDelete.index();
    public static final int ALLOWEDIT = AttributesEnum.AllowEdit.index();
    public static final int ALLOWSUPERVISE = AttributesEnum.AllowSupervise.index();
    public static final int VIEWSCANFILE = AttributesEnum.ViewScanFile.index();
    public static final int SCANFILE = AttributesEnum.ScanFile.index();
    public static final int ALLOWUNSUPERVISE = AttributesEnum.AllowUnsupervise.index();
    public static final int ALLOWCANCEL = AttributesEnum.AllowCancel.index();
    public static final int ALLOWEDITOTHER = AttributesEnum.AllowEditOther.index();
    public static final int ALLOWPRINT = AttributesEnum.AllowPrint.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TXTAGLCOUNT = AttributesEnum.txtAGLCount.index();
    public static final int MODULEID = AttributesEnum.ModuleId.index();
    public static final int ACCESSTYPE = AttributesEnum.AccessType.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int ACTIONCATEGORYID = AttributesEnum.ActionCategoryId.index();
    public static final int MODULEACTIONMAST = AttributesEnum.ModuleActionMast.index();
    public static final int ACTIONNAME = AttributesEnum.ActionName.index();
    public static final int TXTISSUPERVISED = AttributesEnum.txtIsSupervised.index();
    public static final int SYSMODULEDETAILVO = AttributesEnum.SysModuleDetailVO.index();
    public static final int SYSACTIONGROUPHEADERVO = AttributesEnum.SysActionGroupHeaderVO.index();
    public static final int SYSACTIONGROUPLINESCOMPANYVO = AttributesEnum.SysActionGroupLinesCompanyVO.index();
    public static final int ACCSYSACTIONGROUPMODULEQVO = AttributesEnum.AccSysActionGroupModuleQVO.index();
    public static final int ACCSYSUSERACCESSTYPEVO = AttributesEnum.AccSysUserAccessTypeVO.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysActionGroupLinesVORowImpl() {
    }

    /**
     * Gets SysActionGroupLines entity object.
     * @return the SysActionGroupLines
     */
    public SysActionGroupLinesImpl getSysActionGroupLines() {
        return (SysActionGroupLinesImpl) getEntity(ENTITY_SYSACTIONGROUPLINES);
    }

    /**
     * Gets SysModuleDetail entity object.
     * @return the SysModuleDetail
     */
    public EntityImpl getSysModuleDetail() {
        return (EntityImpl) getEntity(ENTITY_SYSMODULEDETAIL);
    }

    /**
     * Gets the attribute value for GROUP_LINES_SNO using the alias name GroupLinesSno.
     * @return the GROUP_LINES_SNO
     */
    public Long getGroupLinesSno() {
        return (Long) getAttributeInternal(GROUPLINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_LINES_SNO using the alias name GroupLinesSno.
     * @param value value to set the GROUP_LINES_SNO
     */
    public void setGroupLinesSno(Long value) {
        setAttributeInternal(GROUPLINESSNO, value);
    }

    /**
     * Gets the attribute value for GROUP_HEADER_SNO using the alias name GroupHeaderSno.
     * @return the GROUP_HEADER_SNO
     */
    public Long getGroupHeaderSno() {
        return (Long) getAttributeInternal(GROUPHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_HEADER_SNO using the alias name GroupHeaderSno.
     * @param value value to set the GROUP_HEADER_SNO
     */
    public void setGroupHeaderSno(Long value) {
        setAttributeInternal(GROUPHEADERSNO, value);
    }

    /**
     * Gets the attribute value for MODULE_ACTION using the alias name ModuleAction.
     * @return the MODULE_ACTION
     */
    public String getModuleAction() {
        return (String) getAttributeInternal(MODULEACTION);
    }

    /**
     * Sets <code>value</code> as attribute value for MODULE_ACTION using the alias name ModuleAction.
     * @param value value to set the MODULE_ACTION
     */
    public void setModuleAction(String value) {
        setAttributeInternal(MODULEACTION, value);
    }

    /**
     * Gets the attribute value for IS_ALLOW using the alias name IsAllow.
     * @return the IS_ALLOW
     */
    public String getIsAllow() {
        return (String) getAttributeInternal(ISALLOW);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_ALLOW using the alias name IsAllow.
     * @param value value to set the IS_ALLOW
     */
    public void setIsAllow(String value) {
        setAttributeInternal(ISALLOW, value);
    }

    /**
     * Gets the attribute value for ALLOW_ADD using the alias name AllowAdd.
     * @return the ALLOW_ADD
     */
    public String getAllowAdd() {
        return (String) getAttributeInternal(ALLOWADD);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_ADD using the alias name AllowAdd.
     * @param value value to set the ALLOW_ADD
     */
    public void setAllowAdd(String value) {
        setAttributeInternal(ALLOWADD, value);
    }

    /**
     * Gets the attribute value for ALLOW_DELETE using the alias name AllowDelete.
     * @return the ALLOW_DELETE
     */
    public String getAllowDelete() {
        return (String) getAttributeInternal(ALLOWDELETE);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_DELETE using the alias name AllowDelete.
     * @param value value to set the ALLOW_DELETE
     */
    public void setAllowDelete(String value) {
        setAttributeInternal(ALLOWDELETE, value);
    }

    /**
     * Gets the attribute value for ALLOW_EDIT using the alias name AllowEdit.
     * @return the ALLOW_EDIT
     */
    public String getAllowEdit() {
        return (String) getAttributeInternal(ALLOWEDIT);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_EDIT using the alias name AllowEdit.
     * @param value value to set the ALLOW_EDIT
     */
    public void setAllowEdit(String value) {
        setAttributeInternal(ALLOWEDIT, value);
    }

    /**
     * Gets the attribute value for ALLOW_SUPERVISE using the alias name AllowSupervise.
     * @return the ALLOW_SUPERVISE
     */
    public String getAllowSupervise() {
        return (String) getAttributeInternal(ALLOWSUPERVISE);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_SUPERVISE using the alias name AllowSupervise.
     * @param value value to set the ALLOW_SUPERVISE
     */
    public void setAllowSupervise(String value) {
        setAttributeInternal(ALLOWSUPERVISE, value);
    }

    /**
     * Gets the attribute value for VIEW_SCAN_FILE using the alias name ViewScanFile.
     * @return the VIEW_SCAN_FILE
     */
    public String getViewScanFile() {
        return (String) getAttributeInternal(VIEWSCANFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for VIEW_SCAN_FILE using the alias name ViewScanFile.
     * @param value value to set the VIEW_SCAN_FILE
     */
    public void setViewScanFile(String value) {
        setAttributeInternal(VIEWSCANFILE, value);
    }

    /**
     * Gets the attribute value for SCAN_FILE using the alias name ScanFile.
     * @return the SCAN_FILE
     */
    public String getScanFile() {
        return (String) getAttributeInternal(SCANFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for SCAN_FILE using the alias name ScanFile.
     * @param value value to set the SCAN_FILE
     */
    public void setScanFile(String value) {
        setAttributeInternal(SCANFILE, value);
    }

    /**
     * Gets the attribute value for ALLOW_UNSUPERVISE using the alias name AllowUnsupervise.
     * @return the ALLOW_UNSUPERVISE
     */
    public String getAllowUnsupervise() {
        return (String) getAttributeInternal(ALLOWUNSUPERVISE);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_UNSUPERVISE using the alias name AllowUnsupervise.
     * @param value value to set the ALLOW_UNSUPERVISE
     */
    public void setAllowUnsupervise(String value) {
        setAttributeInternal(ALLOWUNSUPERVISE, value);
    }

    /**
     * Gets the attribute value for ALLOW_CANCEL using the alias name AllowCancel.
     * @return the ALLOW_CANCEL
     */
    public String getAllowCancel() {
        return (String) getAttributeInternal(ALLOWCANCEL);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_CANCEL using the alias name AllowCancel.
     * @param value value to set the ALLOW_CANCEL
     */
    public void setAllowCancel(String value) {
        setAttributeInternal(ALLOWCANCEL, value);
    }

    /**
     * Gets the attribute value for ALLOW_EDIT_OTHER using the alias name AllowEditOther.
     * @return the ALLOW_EDIT_OTHER
     */
    public String getAllowEditOther() {
        return (String) getAttributeInternal(ALLOWEDITOTHER);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_EDIT_OTHER using the alias name AllowEditOther.
     * @param value value to set the ALLOW_EDIT_OTHER
     */
    public void setAllowEditOther(String value) {
        setAttributeInternal(ALLOWEDITOTHER, value);
    }

    /**
     * Gets the attribute value for ALLOW_PRINT using the alias name AllowPrint.
     * @return the ALLOW_PRINT
     */
    public String getAllowPrint() {
        return (String) getAttributeInternal(ALLOWPRINT);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_PRINT using the alias name AllowPrint.
     * @param value value to set the ALLOW_PRINT
     */
    public void setAllowPrint(String value) {
        setAttributeInternal(ALLOWPRINT, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtAGLCount.
     * @return the txtAGLCount
     */
    public BigDecimal gettxtAGLCount() {
        return (BigDecimal) getAttributeInternal(TXTAGLCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtAGLCount.
     * @param value value to set the  txtAGLCount
     */
    public void settxtAGLCount(BigDecimal value) {
        setAttributeInternal(TXTAGLCOUNT, value);
    }

    /**
     * Gets the attribute value for MODULE_ID using the alias name ModuleId.
     * @return the MODULE_ID
     */
    public String getModuleId() {
        return (String) getAttributeInternal(MODULEID);
    }

    /**
     * Sets <code>value</code> as attribute value for MODULE_ID using the alias name ModuleId.
     * @param value value to set the MODULE_ID
     */
    public void setModuleId(String value) {
        setAttributeInternal(MODULEID, value);
    }

    /**
     * Gets the attribute value for ACCESS_TYPE using the alias name AccessType.
     * @return the ACCESS_TYPE
     */
    public String getAccessType() {
        return (String) getAttributeInternal(ACCESSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESS_TYPE using the alias name AccessType.
     * @param value value to set the ACCESS_TYPE
     */
    public void setAccessType(String value) {
        setAttributeInternal(ACCESSTYPE, value);
    }

    /**
     * Gets the attribute value for IS_ACTIVE using the alias name IsActive.
     * @return the IS_ACTIVE
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_ACTIVE using the alias name IsActive.
     * @param value value to set the IS_ACTIVE
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for ACTION_CATEGORY_ID using the alias name ActionCategoryId.
     * @return the ACTION_CATEGORY_ID
     */
    public Integer getActionCategoryId() {
        return (Integer) getAttributeInternal(ACTIONCATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_CATEGORY_ID using the alias name ActionCategoryId.
     * @param value value to set the ACTION_CATEGORY_ID
     */
    public void setActionCategoryId(Integer value) {
        setAttributeInternal(ACTIONCATEGORYID, value);
    }

    /**
     * Gets the attribute value for MODULE_ACTION using the alias name ModuleActionMast.
     * @return the MODULE_ACTION
     */
    public String getModuleActionMast() {
        return (String) getAttributeInternal(MODULEACTIONMAST);
    }

    /**
     * Sets <code>value</code> as attribute value for MODULE_ACTION using the alias name ModuleActionMast.
     * @param value value to set the MODULE_ACTION
     */
    public void setModuleActionMast(String value) {
        setAttributeInternal(MODULEACTIONMAST, value);
    }

    /**
     * Gets the attribute value for ACTION_NAME using the alias name ActionName.
     * @return the ACTION_NAME
     */
    public String getActionName() {
        return (String) getAttributeInternal(ACTIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_NAME using the alias name ActionName.
     * @param value value to set the ACTION_NAME
     */
    public void setActionName(String value) {
        setAttributeInternal(ACTIONNAME, value);
    }

    /**
     * Gets the attribute value for txt_Is_Supervised using the alias name txtIsSupervised.
     * @return the txt_Is_Supervised
     */
    public String gettxtIsSupervised() {
        return (String) getAttributeInternal(TXTISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Is_Supervised using the alias name txtIsSupervised.
     * @param value value to set the txt_Is_Supervised
     */
    public void settxtIsSupervised(String value) {
        setAttributeInternal(TXTISSUPERVISED, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SysModuleDetailVO.
     */
    public Row getSysModuleDetailVO() {
        return (Row) getAttributeInternal(SYSMODULEDETAILVO);
    }

    /**
     * Sets the master-detail link SysModuleDetailVO between this object and <code>value</code>.
     */
    public void setSysModuleDetailVO(Row value) {
        setAttributeInternal(SYSMODULEDETAILVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SysActionGroupHeaderVO.
     */
    public Row getSysActionGroupHeaderVO() {
        return (Row) getAttributeInternal(SYSACTIONGROUPHEADERVO);
    }

    /**
     * Sets the master-detail link SysActionGroupHeaderVO between this object and <code>value</code>.
     */
    public void setSysActionGroupHeaderVO(Row value) {
        setAttributeInternal(SYSACTIONGROUPHEADERVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupLinesCompanyVO.
     */
    public RowIterator getSysActionGroupLinesCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPLINESCOMPANYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysActionGroupModuleQVO.
     */
    public RowSet getAccSysActionGroupModuleQVO() {
        return (RowSet) getAttributeInternal(ACCSYSACTIONGROUPMODULEQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserAccessTypeVO.
     */
    public RowSet getAccSysUserAccessTypeVO() {
        return (RowSet) getAttributeInternal(ACCSYSUSERACCESSTYPEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValueVO.
     */
    public RowSet getAccSysGeneralValueVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEVO);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getSysActionGroupHeaderVO().getAttribute("IsSupervised") .equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

