package erpadm.modeladm.admvo;

import erpadm.modeladm.admeo.SysActionGroupHeaderImpl;

import erpadm.modeladm.admvo.common.SysActionGroupHeaderVORow;

import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 14 22:04:31 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysActionGroupHeaderVORowImpl extends ViewRowImpl implements SysActionGroupHeaderVORow {


    public static final int ENTITY_SYSACTIONGROUPHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GroupHeaderSno,
        GroupHeaderCode,
        ActionGroupName,
        StartDate,
        EndDate,
        IsActive,
        Remarks,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        IsSupervised,
        SupervisedDate,
        IsUnsupervised,
        UnSupervisedDate,
        SupervisedBy,
        UnSupervisedBy,
        CompanyId,
        DocumentDate,
        AccessType,
        txtSelected,
        txtCountGroup,
        SysActionGroupLinesVO,
        SysActionGroupCompanyVO,
        SysActionGroupUserVO,
        AccSysUserAccessTypeVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GROUPHEADERSNO = AttributesEnum.GroupHeaderSno.index();
    public static final int GROUPHEADERCODE = AttributesEnum.GroupHeaderCode.index();
    public static final int ACTIONGROUPNAME = AttributesEnum.ActionGroupName.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int DOCUMENTDATE = AttributesEnum.DocumentDate.index();
    public static final int ACCESSTYPE = AttributesEnum.AccessType.index();
    public static final int TXTSELECTED = AttributesEnum.txtSelected.index();
    public static final int TXTCOUNTGROUP = AttributesEnum.txtCountGroup.index();
    public static final int SYSACTIONGROUPLINESVO = AttributesEnum.SysActionGroupLinesVO.index();
    public static final int SYSACTIONGROUPCOMPANYVO = AttributesEnum.SysActionGroupCompanyVO.index();
    public static final int SYSACTIONGROUPUSERVO = AttributesEnum.SysActionGroupUserVO.index();
    public static final int ACCSYSUSERACCESSTYPEVO = AttributesEnum.AccSysUserAccessTypeVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysActionGroupHeaderVORowImpl() {
    }

    /**
     * Gets SysActionGroupHeader entity object.
     * @return the SysActionGroupHeader
     */
    public SysActionGroupHeaderImpl getSysActionGroupHeader() {
        return (SysActionGroupHeaderImpl) getEntity(ENTITY_SYSACTIONGROUPHEADER);
    }

    /**
     * Gets the attribute value for GROUP_HEADER_SNO using the alias name GroupHeaderSno.
     * @return the GROUP_HEADER_SNO
     */
    public Integer getGroupHeaderSno() {
        return (Integer) getAttributeInternal(GROUPHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_HEADER_SNO using the alias name GroupHeaderSno.
     * @param value value to set the GROUP_HEADER_SNO
     */
    public void setGroupHeaderSno(Integer value) {
        setAttributeInternal(GROUPHEADERSNO, value);
    }

    /**
     * Gets the attribute value for GROUP_HEADER_CODE using the alias name GroupHeaderCode.
     * @return the GROUP_HEADER_CODE
     */
    public Integer getGroupHeaderCode() {
        return (Integer) getAttributeInternal(GROUPHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_HEADER_CODE using the alias name GroupHeaderCode.
     * @param value value to set the GROUP_HEADER_CODE
     */
    public void setGroupHeaderCode(Integer value) {
        setAttributeInternal(GROUPHEADERCODE, value);
    }

    /**
     * Gets the attribute value for ACTION_GROUP_NAME using the alias name ActionGroupName.
     * @return the ACTION_GROUP_NAME
     */
    public String getActionGroupName() {
        return (String) getAttributeInternal(ACTIONGROUPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_GROUP_NAME using the alias name ActionGroupName.
     * @param value value to set the ACTION_GROUP_NAME
     */
    public void setActionGroupName(String value) {
        setAttributeInternal(ACTIONGROUPNAME, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for IS_ACTIVE using the alias name IsActive.
     * @return the IS_ACTIVE
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_ACTIVE using the alias name IsActive.
     * @param value value to set the IS_ACTIVE
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @return the IS_SUPERVISED
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @param value value to set the IS_SUPERVISED
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @return the SUPERVISED_DATE
     */
    public Timestamp getSupervisedDate() {
        return (Timestamp) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @param value value to set the SUPERVISED_DATE
     */
    public void setSupervisedDate(Timestamp value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @return the IS_UNSUPERVISED
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @param value value to set the IS_UNSUPERVISED
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @return the UN_SUPERVISED_DATE
     */
    public Timestamp getUnSupervisedDate() {
        return (Timestamp) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @param value value to set the UN_SUPERVISED_DATE
     */
    public void setUnSupervisedDate(Timestamp value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @return the SUPERVISED_BY
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @param value value to set the SUPERVISED_BY
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @return the UN_SUPERVISED_BY
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @param value value to set the UN_SUPERVISED_BY
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_DATE using the alias name DocumentDate.
     * @return the DOCUMENT_DATE
     */
    public Date getDocumentDate() {
        return (Date) getAttributeInternal(DOCUMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_DATE using the alias name DocumentDate.
     * @param value value to set the DOCUMENT_DATE
     */
    public void setDocumentDate(Date value) {
        setAttributeInternal(DOCUMENTDATE, value);
    }

    /**
     * Gets the attribute value for ACCESS_TYPE using the alias name AccessType.
     * @return the ACCESS_TYPE
     */
    public String getAccessType() {
        return (String) getAttributeInternal(ACCESSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESS_TYPE using the alias name AccessType.
     * @param value value to set the ACCESS_TYPE
     */
    public void setAccessType(String value) {
        setAttributeInternal(ACCESSTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSelected.
     * @return the txtSelected
     */
    public String gettxtSelected() {
        return (String) getAttributeInternal(TXTSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSelected.
     * @param value value to set the  txtSelected
     */
    public void settxtSelected(String value) {
        setAttributeInternal(TXTSELECTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCountGroup.
     * @return the txtCountGroup
     */
    public Integer gettxtCountGroup() {
        return (Integer) getAttributeInternal(TXTCOUNTGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCountGroup.
     * @param value value to set the  txtCountGroup
     */
    public void settxtCountGroup(Integer value) {
        setAttributeInternal(TXTCOUNTGROUP, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupLinesVO.
     */
    public RowIterator getSysActionGroupLinesVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPLINESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupCompanyVO.
     */
    public RowIterator getSysActionGroupCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPCOMPANYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupUserVO.
     */
    public RowIterator getSysActionGroupUserVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPUSERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserAccessTypeVO.
     */
    public RowSet getAccSysUserAccessTypeVO() {
        return (RowSet) getAttributeInternal(ACCSYSUSERACCESSTYPEVO);
    }
    public void doAssignERPOneGroupToUser() {
        getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
        ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysActionGroupUserDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("GroupHeaderSno", getGroupHeaderSno());
            //cr.setAttribute("ModuleId", getModuleId());
            //cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getIsSupervised().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

