package erpadm.modeladm.admvo;

import erpadm.modeladm.admvo.common.SysModuleDetailVORow;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 27 22:29:54 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysModuleDetailVORowImpl extends ViewRowImpl implements SysModuleDetailVORow {


    public static final int ENTITY_SYSMODULEDETAIL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ModuleId,
        ActionId,
        ModuleAction,
        ActionType,
        ParentAction,
        ActionName,
        Active,
        Seq,
        ActionRuntime,
        txtSelected,
        txtCount,
        ActionCategoryId,
        SysUsersModuleVO,
        SysActionGroupLinesVO,
        AccSysModuleVO,
        AccSysGeneralValueVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MODULEID = AttributesEnum.ModuleId.index();
    public static final int ACTIONID = AttributesEnum.ActionId.index();
    public static final int MODULEACTION = AttributesEnum.ModuleAction.index();
    public static final int ACTIONTYPE = AttributesEnum.ActionType.index();
    public static final int PARENTACTION = AttributesEnum.ParentAction.index();
    public static final int ACTIONNAME = AttributesEnum.ActionName.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int SEQ = AttributesEnum.Seq.index();
    public static final int ACTIONRUNTIME = AttributesEnum.ActionRuntime.index();
    public static final int TXTSELECTED = AttributesEnum.txtSelected.index();
    public static final int TXTCOUNT = AttributesEnum.txtCount.index();
    public static final int ACTIONCATEGORYID = AttributesEnum.ActionCategoryId.index();
    public static final int SYSUSERSMODULEVO = AttributesEnum.SysUsersModuleVO.index();
    public static final int SYSACTIONGROUPLINESVO = AttributesEnum.SysActionGroupLinesVO.index();
    public static final int ACCSYSMODULEVO = AttributesEnum.AccSysModuleVO.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysModuleDetailVORowImpl() {
    }

    /**
     * Gets SysModuleDetail entity object.
     * @return the SysModuleDetail
     */
    public EntityImpl getSysModuleDetail() {
        return (EntityImpl) getEntity(ENTITY_SYSMODULEDETAIL);
    }

    /**
     * Gets the attribute value for MODULE_ID using the alias name ModuleId.
     * @return the MODULE_ID
     */
    public String getModuleId() {
        return (String) getAttributeInternal(MODULEID);
    }

    /**
     * Sets <code>value</code> as attribute value for MODULE_ID using the alias name ModuleId.
     * @param value value to set the MODULE_ID
     */
    public void setModuleId(String value) {
        setAttributeInternal(MODULEID, value);
    }

    /**
     * Gets the attribute value for ACTION_ID using the alias name ActionId.
     * @return the ACTION_ID
     */
    public String getActionId() {
        return (String) getAttributeInternal(ACTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_ID using the alias name ActionId.
     * @param value value to set the ACTION_ID
     */
    public void setActionId(String value) {
        setAttributeInternal(ACTIONID, value);
    }

    /**
     * Gets the attribute value for MODULE_ACTION using the alias name ModuleAction.
     * @return the MODULE_ACTION
     */
    public String getModuleAction() {
        return (String) getAttributeInternal(MODULEACTION);
    }

    /**
     * Sets <code>value</code> as attribute value for MODULE_ACTION using the alias name ModuleAction.
     * @param value value to set the MODULE_ACTION
     */
    public void setModuleAction(String value) {
        setAttributeInternal(MODULEACTION, value);
    }

    /**
     * Gets the attribute value for ACTION_TYPE using the alias name ActionType.
     * @return the ACTION_TYPE
     */
    public String getActionType() {
        return (String) getAttributeInternal(ACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_TYPE using the alias name ActionType.
     * @param value value to set the ACTION_TYPE
     */
    public void setActionType(String value) {
        setAttributeInternal(ACTIONTYPE, value);
    }


    /**
     * Gets the attribute value for PARENT_ACTION using the alias name ParentAction.
     * @return the PARENT_ACTION
     */
    public String getParentAction() {
        return (String) getAttributeInternal(PARENTACTION);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_ACTION using the alias name ParentAction.
     * @param value value to set the PARENT_ACTION
     */
    public void setParentAction(String value) {
        setAttributeInternal(PARENTACTION, value);
    }

    /**
     * Gets the attribute value for ACTION_NAME using the alias name ActionName.
     * @return the ACTION_NAME
     */
    public String getActionName() {
        return (String) getAttributeInternal(ACTIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_NAME using the alias name ActionName.
     * @param value value to set the ACTION_NAME
     */
    public void setActionName(String value) {
        setAttributeInternal(ACTIONNAME, value);
    }

    /**
     * Gets the attribute value for ACTIVE using the alias name Active.
     * @return the ACTIVE
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE using the alias name Active.
     * @param value value to set the ACTIVE
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for SEQ using the alias name Seq.
     * @return the SEQ
     */
    public BigDecimal getSeq() {
        return (BigDecimal) getAttributeInternal(SEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for SEQ using the alias name Seq.
     * @param value value to set the SEQ
     */
    public void setSeq(BigDecimal value) {
        setAttributeInternal(SEQ, value);
    }

    /**
     * Gets the attribute value for ACTION_RUNTIME using the alias name ActionRuntime.
     * @return the ACTION_RUNTIME
     */
    public String getActionRuntime() {
        return (String) getAttributeInternal(ACTIONRUNTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_RUNTIME using the alias name ActionRuntime.
     * @param value value to set the ACTION_RUNTIME
     */
    public void setActionRuntime(String value) {
        setAttributeInternal(ACTIONRUNTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSelected.
     * @return the txtSelected
     */
    public String gettxtSelected() {
        return (String) getAttributeInternal(TXTSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSelected.
     * @param value value to set the  txtSelected
     */
    public void settxtSelected(String value) {
        setAttributeInternal(TXTSELECTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCount.
     * @return the txtCount
     */
    public Integer gettxtCount() {
        return (Integer) getAttributeInternal(TXTCOUNT);
    }

    /**
     * Gets the attribute value for ACTION_CATEGORY_ID using the alias name ActionCategoryId.
     * @return the ACTION_CATEGORY_ID
     */
    public Integer getActionCategoryId() {
        return (Integer) getAttributeInternal(ACTIONCATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_CATEGORY_ID using the alias name ActionCategoryId.
     * @param value value to set the ACTION_CATEGORY_ID
     */
    public void setActionCategoryId(Integer value) {
        setAttributeInternal(ACTIONCATEGORYID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysUsersModuleVO.
     */
    public RowIterator getSysUsersModuleVO() {
        return (RowIterator) getAttributeInternal(SYSUSERSMODULEVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupLinesVO.
     */
    public RowIterator getSysActionGroupLinesVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPLINESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysModuleVO.
     */
    public RowSet getAccSysModuleVO() {
        return (RowSet) getAttributeInternal(ACCSYSMODULEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValueVO.
     */
    public RowSet getAccSysGeneralValueVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEVO);
    }

    public void doAssignOneActivityToGroup() {
            /*when we press undo then system unset the current row here we as setting current row that is FIRST*/
            getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
            ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysActionGroupLinesDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("ModuleAction", getModuleAction());
            cr.setAttribute("ModuleId", getModuleId());
            cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
    }
 
    public void doAssignERPOneActivityToUser() {
        /*when we press undo then system unset the current row here we as setting current row that is FIRST*/
            getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
            ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysUsersModuleDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("ModuleAction", getModuleAction());
            cr.setAttribute("ModuleId", getModuleId());
            cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
    }    
}

