package erpadm.modeladm.admvo;

import erpadm.modeladm.admvo.common.SysModuleDetailVO;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 22 18:19:48 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysModuleDetailVOImpl extends ViewObjectImpl implements SysModuleDetailVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SysModuleDetailVOImpl() {
    }

    public void doAssignActivityToGroup() {
        getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
        
        getDBTransaction().commit();
        ViewObject vo = getRootApplicationModule().findViewObject("SysActionGroupLinesDetCRUD");

        RowSetIterator rsi =this.getRowSet();
        rsi.setRangeSize(-1);
       // System.out.println("i am calling");

        for (int i=0;i<rsi.getRowCount();i++) {
            Row r = rsi.getRowAtRangeIndex(i);
            //record might be assigned through single assignment
            if (r.getAttribute("txtSelected")== null || r.getAttribute("txtSelected").toString().equals("N")) {
                r.setAttribute("txtSelected", "Y");
                Row cr = vo.createRow();
                cr.setAttribute("ModuleAction", r.getAttribute("ModuleAction"));
                cr.setAttribute("ModuleId", r.getAttribute("ModuleId"));
                cr.setAttribute("Remarks", "Copied" + r.getAttribute("ModuleAction"));
                vo.insertRow(cr);
            }
        }
        getDBTransaction().commit();
        //vo.executeQuery();
        //executeQuery();
        getDBTransaction().rollback();
    }

    public void doAssignERPActivityToUser() {
        getDBTransaction().getRootApplicationModule().findViewObject("SysUsersCRUD").first();
        
        getDBTransaction().commit();// for my sql
        ViewObject vo = getRootApplicationModule().findViewObject("SysUsersModuleDetCRUD");

        RowSetIterator rsi =this.getRowSet();
        rsi.setRangeSize(-1);
        //System.out.println("i am calling");

        for (int i=0;i<rsi.getRowCount();i++) {
            Row r = rsi.getRowAtRangeIndex(i);
            //record might be assigned through single assignment
            if (r.getAttribute("txtSelected")== null || r.getAttribute("txtSelected").toString().equals("N")) {
                r.setAttribute("txtSelected", "Y");
                Row cr = vo.createRow();
                cr.setAttribute("ModuleAction", r.getAttribute("ModuleAction"));
                cr.setAttribute("ModuleId", r.getAttribute("ModuleId"));
                cr.setAttribute("Remarks", "Copied" + r.getAttribute("ModuleAction"));
                vo.insertRow(cr);
            }
        }
        getDBTransaction().commit();
        //vo.executeQuery();
        //executeQuery();
        getDBTransaction().rollback();
    }
    /**
     * Returns the variable value for P_ADF_GROUP_HEADER_SNO.
     * @return variable value for P_ADF_GROUP_HEADER_SNO
     */
    public Integer getP_ADF_GROUP_HEADER_SNO() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_GROUP_HEADER_SNO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_GROUP_HEADER_SNO.
     * @param value value to bind as P_ADF_GROUP_HEADER_SNO
     */
    public void setP_ADF_GROUP_HEADER_SNO(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_GROUP_HEADER_SNO", value);
    }
    
    @Override
    public void executeEmptyRowSet() {
        // TODO Implement this method
        super.executeEmptyRowSet();
    }

    /**
     * Returns the variable value for P_ADF_USER_ID.
     * @return variable value for P_ADF_USER_ID
     */
    public Integer getP_ADF_USER_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_USER_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_USER_ID.
     * @param value value to bind as P_ADF_USER_ID
     */
    public void setP_ADF_USER_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_USER_ID", value);
    }
}

