package erpadm.modeladm.admvo;

import erpglobals.modelglobals.ERPViewObjectImpl;

import oracle.jbo.ApplicationModule;
import oracle.jbo.ViewObject;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 19 20:03:56 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysPasswordPolicyHeaderVOImpl extends ERPViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SysPasswordPolicyHeaderVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_GLOBAL_COMPANY_ID.
     * @return variable value for P_ADF_GLOBAL_COMPANY_ID
     */
    public Integer getP_ADF_GLOBAL_COMPANY_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_GLOBAL_COMPANY_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_GLOBAL_COMPANY_ID.
     * @param value value to bind as P_ADF_GLOBAL_COMPANY_ID
     */
    public void setP_ADF_GLOBAL_COMPANY_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_GLOBAL_COMPANY_ID", value);
    }

    /**
     * Returns the variable value for P_ADF_POLICY_HEADER_SNO.
     * @return variable value for P_ADF_POLICY_HEADER_SNO
     */
    public Integer getP_ADF_POLICY_HEADER_SNO() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_POLICY_HEADER_SNO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_POLICY_HEADER_SNO.
     * @param value value to bind as P_ADF_POLICY_HEADER_SNO
     */
    public void setP_ADF_POLICY_HEADER_SNO(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_POLICY_HEADER_SNO", value);
    }
    @Override
    public void afterRollback(TransactionEvent transactionEvent) {
        // TODO Implement this method
        setErpViewObjectName("SysPasswordPolicyHeaderCRUD");
        setErpPkColumn("PolicyHeaderSno");
        setErpParameterId("P_ADF_POLICY_HEADER_SNO");
        super.afterRollback(transactionEvent);
    }
}

