package erpadm.modeladm.admvo;

import erpadm.modeladm.admvo.common.SysPasswordParameterVO;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 19 20:21:03 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysPasswordParameterVOImpl extends ViewObjectImpl implements SysPasswordParameterVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SysPasswordParameterVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_POLICY_HEADER_SNO.
     * @return variable value for P_ADF_POLICY_HEADER_SNO
     */
    public Integer getP_ADF_POLICY_HEADER_SNO() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_POLICY_HEADER_SNO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_POLICY_HEADER_SNO.
     * @param value value to bind as P_ADF_POLICY_HEADER_SNO
     */
    public void setP_ADF_POLICY_HEADER_SNO(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_POLICY_HEADER_SNO", value);
    }
 
    public void doErpAssignAllSysPwdParaToPolicy() {
        ViewObject vo = getRootApplicationModule().findViewObject("SysPasswordPolicyLinesDetCRUD");
        RowSetIterator rsi =this.getRowSet();
        rsi.setRangeSize(-1);
        for (int i=0;i<rsi.getRowCount();i++) {
            Row r = rsi.getRowAtRangeIndex(i);
            //record might be assigned through single assignment
            if (r.getAttribute("txtSelected")== null || r.getAttribute("txtSelected").toString().equals("N")) {
                r.setAttribute("txtSelected", "Y");
                Row cr = vo.createRow();
                cr.setAttribute("PasswordParameterSno", r.getAttribute("PasswordParameterSno").toString());
                //cr.setAttribute("ModuleId", r.getAttribute("ModuleId"));
                //cr.setAttribute("Remarks", "Copied" + r.getAttribute("ModuleAction"));
                vo.insertRow(cr);
            }
        }
        getDBTransaction().commit();
        vo.executeQuery();
        this.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }   
}

