package erpadm.modeladm.admvo;

import erpadm.modeladm.admeo.SysUsersImpl;

import erpadm.modeladm.admvo.common.SysUsersVORow;

import java.sql.Timestamp;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 29 19:48:15 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysUsersVORowImpl extends ViewRowImpl implements SysUsersVORow {


    public static final int ENTITY_SYSUSERS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        UserName,
        Passwordd,
        IsLock,
        UserCode,
        ScanPath,
        Email,
        SavePath,
        MobileNo,
        CnicNo,
        IsExpired,
        ExpiryDate,
        LockDate,
        CitySno,
        CountrySno,
        LastLoginDate,
        Dob,
        CreatedBy,
        CreatedDate,
        GenderSno,
        txtCountryName,
        txtCityName,
        PhoneNo,
        LastUpdatedDate,
        LastUpdatedBy,
        Remarks,
        AllowedIpAddress,
        UserTypeSno,
        txtPolicyHeaderSno,
        txtPolicyName,
        AccessType,
        LastName,
        FirstName,
        txtSelected,
        txtCountUser,
        PictureName,
        SysUserPasswordPolicyVO,
        SysUsersModuleVO,
        SysUserCompanyVO,
        SysActionGroupUserVO,
        SysUserGlobalCompanyVO,
        AccSetGenderVO,
        AccSmCountryVO,
        AccSmCityVO,
        AccSysUserTypesVO,
        AccSysPasswordPolicyHeader,
        AccSysUserAccessTypeVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int PASSWORDD = AttributesEnum.Passwordd.index();
    public static final int ISLOCK = AttributesEnum.IsLock.index();
    public static final int USERCODE = AttributesEnum.UserCode.index();
    public static final int SCANPATH = AttributesEnum.ScanPath.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int SAVEPATH = AttributesEnum.SavePath.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int CNICNO = AttributesEnum.CnicNo.index();
    public static final int ISEXPIRED = AttributesEnum.IsExpired.index();
    public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
    public static final int LOCKDATE = AttributesEnum.LockDate.index();
    public static final int CITYSNO = AttributesEnum.CitySno.index();
    public static final int COUNTRYSNO = AttributesEnum.CountrySno.index();
    public static final int LASTLOGINDATE = AttributesEnum.LastLoginDate.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int GENDERSNO = AttributesEnum.GenderSno.index();
    public static final int TXTCOUNTRYNAME = AttributesEnum.txtCountryName.index();
    public static final int TXTCITYNAME = AttributesEnum.txtCityName.index();
    public static final int PHONENO = AttributesEnum.PhoneNo.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ALLOWEDIPADDRESS = AttributesEnum.AllowedIpAddress.index();
    public static final int USERTYPESNO = AttributesEnum.UserTypeSno.index();
    public static final int TXTPOLICYHEADERSNO = AttributesEnum.txtPolicyHeaderSno.index();
    public static final int TXTPOLICYNAME = AttributesEnum.txtPolicyName.index();
    public static final int ACCESSTYPE = AttributesEnum.AccessType.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int TXTSELECTED = AttributesEnum.txtSelected.index();
    public static final int TXTCOUNTUSER = AttributesEnum.txtCountUser.index();
    public static final int PICTURENAME = AttributesEnum.PictureName.index();
    public static final int SYSUSERPASSWORDPOLICYVO = AttributesEnum.SysUserPasswordPolicyVO.index();
    public static final int SYSUSERSMODULEVO = AttributesEnum.SysUsersModuleVO.index();
    public static final int SYSUSERCOMPANYVO = AttributesEnum.SysUserCompanyVO.index();
    public static final int SYSACTIONGROUPUSERVO = AttributesEnum.SysActionGroupUserVO.index();
    public static final int SYSUSERGLOBALCOMPANYVO = AttributesEnum.SysUserGlobalCompanyVO.index();
    public static final int ACCSETGENDERVO = AttributesEnum.AccSetGenderVO.index();
    public static final int ACCSMCOUNTRYVO = AttributesEnum.AccSmCountryVO.index();
    public static final int ACCSMCITYVO = AttributesEnum.AccSmCityVO.index();
    public static final int ACCSYSUSERTYPESVO = AttributesEnum.AccSysUserTypesVO.index();
    public static final int ACCSYSPASSWORDPOLICYHEADER = AttributesEnum.AccSysPasswordPolicyHeader.index();
    public static final int ACCSYSUSERACCESSTYPEVO = AttributesEnum.AccSysUserAccessTypeVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysUsersVORowImpl() {
    }

    /**
     * Gets SysUsers entity object.
     * @return the SysUsers
     */
    public SysUsersImpl getSysUsers() {
        return (SysUsersImpl) getEntity(ENTITY_SYSUSERS);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(Integer value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for PASSWORDD using the alias name Passwordd.
     * @return the PASSWORDD
     */
    public String getPasswordd() {
        return (String) getAttributeInternal(PASSWORDD);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORDD using the alias name Passwordd.
     * @param value value to set the PASSWORDD
     */
    public void setPasswordd(String value) {
        setAttributeInternal(PASSWORDD, value);
    }

    /**
     * Gets the attribute value for IS_LOCK using the alias name IsLock.
     * @return the IS_LOCK
     */
    public String getIsLock() {
        return (String) getAttributeInternal(ISLOCK);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_LOCK using the alias name IsLock.
     * @param value value to set the IS_LOCK
     */
    public void setIsLock(String value) {
        setAttributeInternal(ISLOCK, value);
    }

    /**
     * Gets the attribute value for USER_CODE using the alias name UserCode.
     * @return the USER_CODE
     */
    public String getUserCode() {
        return (String) getAttributeInternal(USERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_CODE using the alias name UserCode.
     * @param value value to set the USER_CODE
     */
    public void setUserCode(String value) {
        setAttributeInternal(USERCODE, value);
    }


    /**
     * Gets the attribute value for SCAN_PATH using the alias name ScanPath.
     * @return the SCAN_PATH
     */
    public String getScanPath() {
        return (String) getAttributeInternal(SCANPATH);
    }

    /**
     * Sets <code>value</code> as attribute value for SCAN_PATH using the alias name ScanPath.
     * @param value value to set the SCAN_PATH
     */
    public void setScanPath(String value) {
        setAttributeInternal(SCANPATH, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for SAVE_PATH using the alias name SavePath.
     * @return the SAVE_PATH
     */
    public String getSavePath() {
        return (String) getAttributeInternal(SAVEPATH);
    }

    /**
     * Sets <code>value</code> as attribute value for SAVE_PATH using the alias name SavePath.
     * @param value value to set the SAVE_PATH
     */
    public void setSavePath(String value) {
        setAttributeInternal(SAVEPATH, value);
    }

    /**
     * Gets the attribute value for MOBILE_NO using the alias name MobileNo.
     * @return the MOBILE_NO
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_NO using the alias name MobileNo.
     * @param value value to set the MOBILE_NO
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for CNIC_NO using the alias name CnicNo.
     * @return the CNIC_NO
     */
    public String getCnicNo() {
        return (String) getAttributeInternal(CNICNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CNIC_NO using the alias name CnicNo.
     * @param value value to set the CNIC_NO
     */
    public void setCnicNo(String value) {
        setAttributeInternal(CNICNO, value);
    }

    /**
     * Gets the attribute value for IS_EXPIRED using the alias name IsExpired.
     * @return the IS_EXPIRED
     */
    public String getIsExpired() {
        return (String) getAttributeInternal(ISEXPIRED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_EXPIRED using the alias name IsExpired.
     * @param value value to set the IS_EXPIRED
     */
    public void setIsExpired(String value) {
        setAttributeInternal(ISEXPIRED, value);
    }

    /**
     * Gets the attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @return the EXPIRY_DATE
     */
    public Timestamp getExpiryDate() {
        return (Timestamp) getAttributeInternal(EXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @param value value to set the EXPIRY_DATE
     */
    public void setExpiryDate(Timestamp value) {
        setAttributeInternal(EXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for LOCK_DATE using the alias name LockDate.
     * @return the LOCK_DATE
     */
    public Timestamp getLockDate() {
        return (Timestamp) getAttributeInternal(LOCKDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCK_DATE using the alias name LockDate.
     * @param value value to set the LOCK_DATE
     */
    public void setLockDate(Timestamp value) {
        setAttributeInternal(LOCKDATE, value);
    }

    /**
     * Gets the attribute value for CITY_SNO using the alias name CitySno.
     * @return the CITY_SNO
     */
    public Integer getCitySno() {
        return (Integer) getAttributeInternal(CITYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_SNO using the alias name CitySno.
     * @param value value to set the CITY_SNO
     */
    public void setCitySno(Integer value) {
        setAttributeInternal(CITYSNO, value);
    }

    /**
     * Gets the attribute value for COUNTRY_SNO using the alias name CountrySno.
     * @return the COUNTRY_SNO
     */
    public Integer getCountrySno() {
        return (Integer) getAttributeInternal(COUNTRYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_SNO using the alias name CountrySno.
     * @param value value to set the COUNTRY_SNO
     */
    public void setCountrySno(Integer value) {
        setAttributeInternal(COUNTRYSNO, value);
    }

    /**
     * Gets the attribute value for LAST_LOGIN_DATE using the alias name LastLoginDate.
     * @return the LAST_LOGIN_DATE
     */
    public Timestamp getLastLoginDate() {
        return (Timestamp) getAttributeInternal(LASTLOGINDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_LOGIN_DATE using the alias name LastLoginDate.
     * @param value value to set the LAST_LOGIN_DATE
     */
    public void setLastLoginDate(Timestamp value) {
        setAttributeInternal(LASTLOGINDATE, value);
    }

    /**
     * Gets the attribute value for DOB using the alias name Dob.
     * @return the DOB
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as attribute value for DOB using the alias name Dob.
     * @param value value to set the DOB
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for GENDER_SNO using the alias name GenderSno.
     * @return the GENDER_SNO
     */
    public Integer getGenderSno() {
        return (Integer) getAttributeInternal(GENDERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GENDER_SNO using the alias name GenderSno.
     * @param value value to set the GENDER_SNO
     */
    public void setGenderSno(Integer value) {
        setAttributeInternal(GENDERSNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCountryName.
     * @return the txtCountryName
     */
    public String gettxtCountryName() {
        return (String) getAttributeInternal(TXTCOUNTRYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCountryName.
     * @param value value to set the  txtCountryName
     */
    public void settxtCountryName(String value) {
        setAttributeInternal(TXTCOUNTRYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCityName.
     * @return the txtCityName
     */
    public String gettxtCityName() {
        return (String) getAttributeInternal(TXTCITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCityName.
     * @param value value to set the  txtCityName
     */
    public void settxtCityName(String value) {
        setAttributeInternal(TXTCITYNAME, value);
    }

    /**
     * Gets the attribute value for PHONE_NO using the alias name PhoneNo.
     * @return the PHONE_NO
     */
    public String getPhoneNo() {
        return (String) getAttributeInternal(PHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE_NO using the alias name PhoneNo.
     * @param value value to set the PHONE_NO
     */
    public void setPhoneNo(String value) {
        setAttributeInternal(PHONENO, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ALLOWED_IP_ADDRESS using the alias name AllowedIpAddress.
     * @return the ALLOWED_IP_ADDRESS
     */
    public String getAllowedIpAddress() {
        return (String) getAttributeInternal(ALLOWEDIPADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWED_IP_ADDRESS using the alias name AllowedIpAddress.
     * @param value value to set the ALLOWED_IP_ADDRESS
     */
    public void setAllowedIpAddress(String value) {
        setAttributeInternal(ALLOWEDIPADDRESS, value);
    }

    /**
     * Gets the attribute value for USER_TYPE_SNO using the alias name UserTypeSno.
     * @return the USER_TYPE_SNO
     */
    public Integer getUserTypeSno() {
        return (Integer) getAttributeInternal(USERTYPESNO);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_TYPE_SNO using the alias name UserTypeSno.
     * @param value value to set the USER_TYPE_SNO
     */
    public void setUserTypeSno(Integer value) {
        setAttributeInternal(USERTYPESNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtPolicyHeaderSno.
     * @return the txtPolicyHeaderSno
     */
    public Integer gettxtPolicyHeaderSno() {
        return (Integer) getAttributeInternal(TXTPOLICYHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtPolicyHeaderSno.
     * @param value value to set the  txtPolicyHeaderSno
     */
    public void settxtPolicyHeaderSno(Integer value) {
        setAttributeInternal(TXTPOLICYHEADERSNO, value);
        if (value==null) {
            return;
       }
        ViewObject vo=getDBTransaction().getRootApplicationModule().findViewObject("SysUserPasswordPolicyDetCRUD");
        vo.reset();
        vo.executeQuery();
        System.out.println(vo.getRowCount()+ "getRowCount vo");
        RowIterator ri = getSysUserPasswordPolicyVO();
        ri.reset();
        System.out.println(ri.getRowCount() + " total row count");
        while (ri.hasNext()) {
            Row r = ri.next();
            if (Integer.parseInt(r.getAttribute("PolicyHeaderSno").toString()) == value) {
                throw new JboException("This policy is already assiged to this user.");
            }
        }
        Row cr = getSysUserPasswordPolicyVO().createRow();
        cr.setAttribute("PolicyHeaderSno", value);
        getSysUserPasswordPolicyVO().insertRow(cr);
        getDBTransaction().commit();
        vo.executeQuery();
    }

    /**
     * Gets the attribute value for the calculated attribute txtPolicyName.
     * @return the txtPolicyName
     */
    public String gettxtPolicyName() {
        return (String) getAttributeInternal(TXTPOLICYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtPolicyName.
     * @param value value to set the  txtPolicyName
     */
    public void settxtPolicyName(String value) {
        setAttributeInternal(TXTPOLICYNAME, value);
    }

    /**
     * Gets the attribute value for ACCESS_TYPE using the alias name AccessType.
     * @return the ACCESS_TYPE
     */
    public String getAccessType() {
        return (String) getAttributeInternal(ACCESSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESS_TYPE using the alias name AccessType.
     * @param value value to set the ACCESS_TYPE
     */
    public void setAccessType(String value) {
        setAttributeInternal(ACCESSTYPE, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSelected.
     * @return the txtSelected
     */
    public String gettxtSelected() {
        return (String) getAttributeInternal(TXTSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSelected.
     * @param value value to set the  txtSelected
     */
    public void settxtSelected(String value) {
        setAttributeInternal(TXTSELECTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCountUser.
     * @return the txtCountUser
     */
    public Integer gettxtCountUser() {
        return (Integer) getAttributeInternal(TXTCOUNTUSER);
    }

    /**
     * Gets the attribute value for PICTURE_NAME using the alias name PictureName.
     * @return the PICTURE_NAME
     */
    public String getPictureName() {
        return (String) getAttributeInternal(PICTURENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PICTURE_NAME using the alias name PictureName.
     * @param value value to set the PICTURE_NAME
     */
    public void setPictureName(String value) {
        setAttributeInternal(PICTURENAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysUserPasswordPolicyVO.
     */
    public RowIterator getSysUserPasswordPolicyVO() {
        return (RowIterator) getAttributeInternal(SYSUSERPASSWORDPOLICYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysUsersModuleVO.
     */
    public RowIterator getSysUsersModuleVO() {
        return (RowIterator) getAttributeInternal(SYSUSERSMODULEVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysUserCompanyVO.
     */
    public RowIterator getSysUserCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSUSERCOMPANYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysActionGroupUserVO.
     */
    public RowIterator getSysActionGroupUserVO() {
        return (RowIterator) getAttributeInternal(SYSACTIONGROUPUSERVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SysUserGlobalCompanyVO.
     */
    public RowIterator getSysUserGlobalCompanyVO() {
        return (RowIterator) getAttributeInternal(SYSUSERGLOBALCOMPANYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSetGenderVO.
     */
    public RowSet getAccSetGenderVO() {
        return (RowSet) getAttributeInternal(ACCSETGENDERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSmCountryVO.
     */
    public RowSet getAccSmCountryVO() {
        return (RowSet) getAttributeInternal(ACCSMCOUNTRYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSmCityVO.
     */
    public RowSet getAccSmCityVO() {
        return (RowSet) getAttributeInternal(ACCSMCITYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserTypesVO.
     */
    public RowSet getAccSysUserTypesVO() {
        return (RowSet) getAttributeInternal(ACCSYSUSERTYPESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysPasswordPolicyHeader.
     */
    public RowSet getAccSysPasswordPolicyHeader() {
        return (RowSet) getAttributeInternal(ACCSYSPASSWORDPOLICYHEADER);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserAccessTypeVO.
     */
    public RowSet getAccSysUserAccessTypeVO() {
        return (RowSet) getAttributeInternal(ACCSYSUSERACCESSTYPEVO);
    }
 
    public void doAssignERPOneUserToGroup() {
        ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("SysActionGroupUsrGroupDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("UserId", getUserId());
            //cr.setAttribute("ModuleId", getModuleId());
            //cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }   
}

