package erpadm.modeladm.admvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 27 19:07:18 PKT 2019
// ---------------------------------------------------------------------
public interface AdminCompanyVORow extends Row {
    void doAssigERPOneCompToGrpLinAction();

    void doAssignERPOneCompToGroup();

    void doAssignERPOneCompToUserActionLine();

    void doAssignERPOneCompToUser();
}

