package erpadm.modeladm.admvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 23:06:34 PKT 2019
// ---------------------------------------------------------------------
public interface AdminCompanyVO extends ViewObject {
    void doAssignERPCompanyToGroupAction();

    void doAssignERPCompanyToGroup();

    void doAssignERPCompanyToUserAction();

    void executeEmptyRowSet();

    void doAssignERPCompanyToUser();
}

