package erpadm.modeladm.admvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 22 20:52:03 PKT 2019
// ---------------------------------------------------------------------
public interface SysActionGroupHeaderVO extends ViewObject {
    void executeEmptyRowSet();

    void doAssignERPGroupToUser();
}

