package erpadm.modeladm.admvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 14 22:08:28 PKT 2019
// ---------------------------------------------------------------------
public interface SysActionGroupHeaderVORow extends Row {
    void doAssignERPOneGroupToUser();
}

