package erpadm.modeladm.admvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 27 22:32:48 PKT 2019
// ---------------------------------------------------------------------
public interface SysModuleDetailVORow extends Row {
    void doAssignOneActivityToGroup();

    void doAssignERPOneActivityToUser();
}

