package erpadm.modeladm.admvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 22 18:30:13 PKT 2019
// ---------------------------------------------------------------------
public interface SysModuleDetailVO extends ViewObject {
    void doAssignActivityToGroup();

    void executeEmptyRowSet();

    void reset();

    void doAssignERPActivityToUser();
}

