package erpadm.modeladm.admvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 19 20:34:54 PKT 2020
// ---------------------------------------------------------------------
public interface SysPasswordParameterVO extends ViewObject {
    void doErpAssignAllSysPwdParaToPolicy();
}

