package erpadm.modeladm.admvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 20 17:49:47 PKT 2020
// ---------------------------------------------------------------------
public interface SysPasswordParameterVORow extends Row {
    void doErpAssignOneSysPwdParaToPolicy();
}

