package erpadm.modeladm.admvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 18 13:29:33 PKT 2019
// ---------------------------------------------------------------------
public interface SysUsersVORow extends Row {
    void doAssignERPOneUserToGroup();
}

