package erpadm.modeladm.admvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 18 13:18:38 PKT 2019
// ---------------------------------------------------------------------
public interface SysUsersVO extends ViewObject {
    void doAssignERPUserToGroup();
}

